Kong/developer.konghq.com

app/_includes/components/entity_example/format/ui/consumer.html, app/_includes/components/entity_example/format/ui/plugin.html, app/_includes/components/entity_example/format/ui/route.html, app/_includes/components/entity_example/format/ui/service.html, app/_plugins/drops/entity_example/format/deck.rb
Tested UIs and added examples for all the existing entities.
Switch to the Kong Manager/Gateway Manager tab on one of these entity pages:
https://deploy-preview-26--kongdeveloper.netlify.app/kong-entities/consumer/
https://deploy-preview-26--kongdeveloper.netlify.app/kong-entities/service/
https://deploy-preview-26--kongdeveloper.netlify.app/kong-entities/route/
For routes: would it be more helpful to do a `traditional_compat` example and an `expressions` example?
=> UI examples for entities

app/_landing_pages/custom-plugins.yaml, app/_landing_pages/gateway.yaml, app/_landing_pages/gateway/entities.yaml, app/_layouts/default.html, app/_plugins/generators/landing_page/page.rb, app/landing-pages.html
Temporary index page to help us keep track of landing pages that exist without looking in `_landing_pages` and typing the URL manually
=> Add landing page index (temporary)

app/_kong_plugins/basic-auth/index.md, app/_kong_plugins/jwt/index.md, app/_kong_plugins/key-auth/index.md, app/_landing_pages/authentication.yaml
Fixing the authentication landing page to unblock any new dev work. Right now, main is broken and all builds are failing with
```
Liquid Exception: Error rendering {% plugin %} on page: /opt/build/repo/app/_landing_pages/authentication.yaml. The plugin `` doesn't exist. in /opt/build/repo/app/_layouts/landing_page.html"
```
=> Fix auth landing page and add plugin stubs

app/_includes/landing_pages/text.md, app/_landing_pages/deck.yaml, app/_landing_pages/gateway/entities.yaml
Enough people are using `structured_text` with a single text block that it makes sense to add a `text` type.
`structured_text` is intended for showing header + text (plus other types as needed` in a single block
=> Add 'text' block for landing pages

app/_tutorials/add-rate-limiting-for-a-consumer-with-kong-gateway.md, app/_tutorials/add-rate-limiting-tiers-with-kong-gateway.md, app/_tutorials/add-rate-limiting-to-a-service-with-kong-gateway.md, app/_tutorials/enable-key-authentication-on-a-service-with-kong-gateway.md, app/_tutorials/konnect-oidc.md
Fixing a broken tutorial, switching the OIDC tutorial (which doesn't exist on our docs site anymore) with the SSO content that replaced it, and various minor cleanup for tutorials.
The SSO tutorial has prereqs that are unique to it. I added them in as manually for now, didn't want to fail the build. How do we want to handle those?
=> Chore: Cleaning up tutorials

.env.example, README.md, app/_assets/entrypoints/entity_schema.js, app/_assets/javascripts/apps/EntitySchema.vue, app/_assets/javascripts/services/api.js, app/_data/konnect_oas_data.json, app/_data/konnect_product_ids.yml, app/_gateway_entities/consumer.md, app/_gateway_entities/plugin.md, app/_gateway_entities/route.md, app/_gateway_entities/service.md, app/_gateway_entities/target.md, app/_gateway_entities/upstream.md, app/_includes/components/entity_schema.html, app/_includes/sections/schema.html, app/_layouts/default.html, app/_layouts/gateway_entity.html, app/_plugins/drops/entity_schema.rb, app/_plugins/tags/entity_schema.rb, package-lock.json, package.json, vite.config.ts
Render the schema on entity pages using the new
spec-renderer and pulling the information from Konnect.
It works similarly to how the api specs work in the docs.
We keep a file `app/_data/konnect_oas_data.json` with the products'
information we have in Konnect so we can retrieve their API specs.
The file `app/_data/konnect_product_ids.yml` contains a mapping
of each API spec and its correpsonding product id in Konnect. This
provides a way to access and filter them easily.
The schema is rendered using a vue component that requires 3 arguments:
* konnect product id
* the version id of the specific product
* the path to the schema in the spec
The platform pulls this information from the different configuration
files based on the following metadata in a page's frontmatter:
```
schema:
api: …
```
=> Render schemas on gateway entities

app/inso-cli/reference/export.md, app/inso-cli/reference/export_spec.md, app/inso-cli/reference/index.md, app/inso-cli/reference/lint.md, app/inso-cli/reference/lint_spec.md, app/inso-cli/reference/run.md, app/inso-cli/reference/run_collection.md, app/inso-cli/reference/run_test.md, app/inso-cli/reference/script.md
Add Inso-cli reference docs generated from source, not final but at least it gives us an idea of what we can expect to get.
[Inso-reference preview link](https://deploy-preview-124--kongdeveloper.netlify.app/inso-cli/reference/)
**Notes:**
* This is a WIP.
* The work in insomnia that generates these files hasn't been completed yet.
* We need to define the metadata, URL structure,  links structure, formatting, etc.
* How would we handle different versions of these docs with each release?
* Is there anything else we would like the content to have? e.g. examples, we can work with the insomnia to get those included.
=> WIP: Add inso-cli reference docs generated from source

app/_includes/landing_pages/header.md, app/_includes/tier.html, app/_includes/uses.html
Render tier badges on landing pages under the h1.
For it work, the page must have the product and the tier specified in the metadata, e.g.:
```
products:
- insomnia
tier: team
``` 
```
products:
- gateway
tier: enterprise
``` 
The tier should match the corresponding key defined in the product metadata files, e.g [insomnia](https://github.com/Kong/developer.konghq.com/blob/main/app/_data/products/insomnia.yml#L2-L11), [gateway](https://github.com/Kong/developer.konghq.com/blob/main/app/_data/products/gateway.yml#L8-L11).
=> Display badges in landing pages under the h1

.github/CODEOWNERS, .github/workflows/check-for-changes-in-docs-repo.yml, tools/track-docs-changes/README.md, tools/track-docs-changes/index.js, tools/track-docs-changes/package-lock.json, tools/track-docs-changes/package.json
Add tool that check for changes in files in the docs repo that are used as sources for dev site pages.
```
app/_gateway_entities/consumer.md:
- app/_src/gateway/key-concepts/consumers.md
app/_gateway_entities/service.md:
- app/_src/gateway/key-concepts/services.md
- app/_src/gateway/get-started/index.md
```
1. Read `./config/sources.yml` to build a mapping of the files in the docs repo that serve as the source for dev site pages.
2. Check for changes made to the source files in the docs repository (specify the relative path to the docs repository using the environment variable `DOCS_PATH`) over the past `DAYS_TO_CHECK_FOR_DOCS_CHANGES` days.
3. For each dev site page specified in `./config/sources.yml`, it outputs:
* The file path corresponding to each source in the docs repository.
* For …
=> Track changed docs

Makefile, tools/frontmatter-validator/index.js, tools/frontmatter-validator/package.json
Add `make validate-frontmatters` and run it as part of `make run`, it takes less than 0.38s.
Its dependencies are installed as part of `make install`.
=> Run frontmatter validations on run

app/_gateway_entities/target.md, app/_includes/components/entity_example/format/ui.md
Pulled from here
https://github.com/Kong/developer.konghq.com/pull/168
=> GW Entity Targets

app/_data/plugins/ai-proxy.yaml, app/_includes/icon_false.html, app/_includes/icon_true.html, app/_includes/landing_pages/feature_table.md, app/_includes/plugins/ai-proxy/tables/supported-providers.html
=> AI Proxy: changed icons for supported providers table

app/_gateway_entities/consumer.md, app/_gateway_entities/route.md, app/_gateway_entities/service.md, app/_gateway_entities/target.md, app/_gateway_entities/workspace.md, app/_includes/plugins/ai-proxy/overview.md, app/_landing_pages/gateway.yaml, app/_landing_pages/gateway/rate-limiting.yaml, app/_landing_pages/kic/rate-limiting.yaml, app/_landing_pages/mesh/rate-limiting.yaml, app/deck/distributed-config.md, app/deck/manage-deck-with-docker.md, app/deck/object-defaults.md, app/gateway/routing/expressions.md, app/index.html, app/insomnia/api-specs.md, app/insomnia/cloud-sync.md, app/insomnia/data-security.md, app/insomnia/git-sync.md, app/insomnia/incident-response.md, app/insomnia/local-vault.md, app/insomnia/scratch-pad.md, app/insomnia/storage.md, app/insomnia/version-control.md, app/plugins/protocols.md
=> QA (landing pages & reference)

app/_how-tos/add-rate-limiting-to-a-service-with-kong-gateway.md, app/_how-tos/create-a-custom-webhook-slack-with-kong-gateway.md, app/_includes/prereqs/event-hook/slack.md
=> QA: how-tos

app/_includes/components/entity_example/format/snippets/terraform.md, app/_plugins/drops/entity_example/presenters/terraform.rb, app/_plugins/drops/entity_example/utils/variable_replacer.rb
Renders as:
```
header_value = var.anthropic_api_key
```
```
This example requires the following variables to be added to your manifest. You can specify values at runtime by setting TF_VAR_name=value.
variable "anthropic_api_key" {
type = string
}
```
/plugins/ai-proxy/examples/anthropic-chat-route/
=> Add variable support to Terraform examples

app/_includes/components/feature_table.html, app/_includes/landing_pages/feature_table.md, app/_includes/plugins/table.html, app/_plugins/blocks/feature_table.rb
Takes a yaml as input (in the same way the component for landing_pages does, it's using the same template) and renders a table.
I added an extra optional config called `item_title`  in case you want to render a title on the first column.
example usage:
```
{% feature_table %}
item_title: Backend
columns:
- title: Kong Gateway OSS
key: oss
- title: Kong Gateway Enterprise
key: enterprise
- title: Uses Vault entity
key: uses_vault
- title: Konnect supported
key: supports_konnect
features:
- title: Environment variable
url: /how-to/store-secrets-as-env-variables/
oss: true
enterprise: true
supports_konnect: true
{% endfeature_table %}
```
this renders:
=> Add {% feature_table %} block

.github/pull_request_template.md
Don't need the square brackets because GH auto-links the issue by its number.
=> fix: Remove square brackets from PR template issue number [skip ci]

app/_data/kong-conf/3.4.json, app/_data/kong-conf/3.5.json, app/_data/kong-conf/3.6.json, app/_data/kong-conf/3.7.json, app/_data/kong-conf/3.8.json, app/_data/kong-conf/3.9.json, app/_includes/components/kong_config_table.html, app/_plugins/blocks/kong_config_table.rb, app/_plugins/drops/kong_config_table.rb, app/gateway/ssl-certificates.md, tools/kong-conf-to-json/README.md, tools/kong-conf-to-json/package-lock.json, tools/kong-conf-to-json/package.json, tools/kong-conf-to-json/run.js
Fixes [issue](https://github.com/Kong/developer.konghq.com/issues/283)
First draft.
I've added a tool that transforms the kong.conf file and stores a json representation of it (I generated it for 3.4 - 3.9).
We could also render another column with the default value if we want given that's already available.
Description is optional, it pulls the one in the field if none given.
I've rendered the env variable below the field.
It pulls the `kong..conf` json representation based on the page's version.
* if the page doesn't have a version, it uses latest
* if the page is unreleased, it uses latest
**Questions**
* Do we want to add a `set_env_variables: true` to render them or do we want to always render them? 
* I ignore fields that are present instead of making the build fail just because a …
=> Add kong conf table

app/_data/control_plane_request.yml, app/_includes/control_plane_request.html, app/_plugins/blocks/control_plane_request.rb, app/_plugins/drops/control_plane_request.rb
Usage:
```
{% control_plane_request %}
url: /rbac/users
method: POST
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Kong-Admin-Token: $KONG_ADMIN_TOKEN'
body:
name: $ADMIN_NAME
user_token: $USER_TOKEN
{% endcontrol_plane_request %}
```
Fixes #issue
=> Add {% control_plane_request %}

app/_includes/components/plugin_config_example.html
=> Remove overflow-auto from plugin examples

app/_landing_pages/admin-api.yaml, app/_landing_pages/deck.yaml, app/_landing_pages/kic.yaml, app/_landing_pages/konnect-api.yaml, app/_landing_pages/terraform.yaml, app/_landing_pages/tools.yaml
Tools stub pages to stop link checker from failing.
https://deploy-preview-355--kongdeveloper.netlify.app/tools/
- [ N/A ] Tested how-to docs. If not, note why here. 
- [ N/A ] Updated [sources.yaml](https://github.com/Kong/developer.konghq.com/blob/main/tools/track-docs-changes/config/sources.yml). For more info, review [track docs changes](https://github.com/Kong/developer.konghq.com/tree/main/tools/track-docs-changes)
- [ N/A ] Any new docs link to existing docs.
=> chore: Tools stub pages

.github/styles/frontmatter/Keys.txt, app/_how-tos/store-the-gateway-database-credentials-with-aws-secrets-manager.md, app/_includes/components/prereqs.html, tools/track-docs-changes/config/sources.yml
Fixes #269 
If you want to avoid creating a secret in AWS, I left the `kong-gateway-database` secret I used for testing. If you want to create one, make sure to change the name of the secret in the commands.
You can get temporary credentials by signing in to AWS and clicking Access keys on the AWS access portal.
https://deploy-preview-348--kongdeveloper.netlify.app/how-to/store-the-gateway-database-credentials-with-aws-secrets-manager/
=> Feat: How to configure AWS Secrets for DB

app/_data/schemas/frontmatter/base.json, app/_data/schemas/frontmatter/policy.json, app/_includes/breadcrumbs.html, app/_includes/breadcrumbs_and_links.html, app/_includes/edit_and_issue_links.html, app/_includes/get_help.html, app/_landing_pages/gateway/security.yaml, app/_plugins/generators/data/edit_link/base.rb, app/_plugins/generators/data/search_tags/base.rb, app/_plugins/generators/data/search_tags/policy.rb, app/_plugins/hooks/split_into_sections.rb, app/gateway/security-update-process.md, app/vulnerabilities.md, tools/track-docs-changes/config/sources.yml
Fixes #274 
Questions + ideas + notes:
* This doc is coming from Kong Gateway but the text keeps referring to "Kong Gateway and other Kong products". Can we rephrase this and make it a blanket statement without specifically mentioning Kong Gateway, or do we need to consult with someone in eng to make that decision?
* Leave as-is
* We should mark external links in some way, both in text and in info boxes. The "CVSS" link in this doc is external but there's no way to tell without clicking it.
* Created issue: [External link icons](https://github.com/Kong/developer.konghq.com/issues/342)
* Does this info belong on the dev site? I think yes, because it's no longer just a docs site. On the docs site, I might've said no.
* Yes, it belongs here
@cloudjumpercat - this would be a good doc to link …
=> Security update process doc

app/_how-tos/configure-hashicorp-vault-as-a-vault-backend.md, app/_includes/cleanup/third-party/hashicorp.md, tools/track-docs-changes/config/sources.yml
Questions for reviewers:
- **HashiCorp Vault prereq instructions:**
- Are all the commands too much? Should we rely more on specific verbiage and HashiCorp docs links? Ex. "[Create the `admin-policy.hcl` policy file](https://developer.hashicorp.com/vault/tutorials/policies/policies#write-a-policy). This contains the [permissions you need to create and use secrets](https://developer.hashicorp.com/vault/tutorials/secrets-management/versioned-kv#policy-requirements)" and no commands? I thought by adding more commands, this could help users and the automated tests. However, then we're testing if Hashicorp works...
- **Explanation of config parameters:** 
- Do you wish there was more of an explanation about the config parameters (like host, port, protocol, mount, etc.) and where those values …
=> How to: HashiCorp Vault

app/_how-tos/get-started-with-gateway.md
Found an error in a getting started guide step while using it to test another how-to.
Also updating the upstream load balancing step to update the service instead of creating a new one, as the decK apply error that was preventing this from working has now been fixed. When testing, make sure to update your decK version to the latest one to grab the fix.
https://deploy-preview-376--kongdeveloper.netlify.app/how-to/get-started-with-gateway/
=> Fix getting started guide again

app/_how-tos/install-kgw-securely.md, app/_includes/prereqs/install/amazon-linux.md, app/_includes/prereqs/install/debian.md, app/_includes/prereqs/install/red-hat.md, app/_includes/prereqs/install/ubuntu.md, app/_landing_pages/install.yaml
Install instructions as a series of includes. So we can build landing pages and prererqs for install docs. Everything except RedHat was tested. 
Ticket for platform to support current docs.konghq.com URL rendering thing:
https://github.com/Kong/developer.konghq.com/issues/386
Fixes https://github.com/Kong/developer.konghq.com/issues/388
No preview links available since it is all just includes.
=> Feat: install instructions

.github/styles/base/Dictionary.txt, app/_gateway_entities/vault.md, app/_how-tos/configure-the-konnect-config-store.md
Fixes an issue we talked about on Friday about Config Store not working with kong.conf
https://deploy-preview-385--kongdeveloper.netlify.app/how-to/configure-the-konnect-config-store/#faq
https://deploy-preview-385--kongdeveloper.netlify.app/gateway/entities/vault/#what-can-be-stored-as-a-secret
=> Vault entity fix: Add table with values that can be stored as secrets

app/_kong_plugins/cors/changelog.md, app/_kong_plugins/cors/index.md
Fixes #421 
The plugin was already migrated previously, so this really only moves the changelog.
=> Migrate cors changelog

app/_gateway_entities/vault.md, app/_how-tos/configure-aws-secrets-manager-as-a-vault-backend-with-vault-entity.md, app/_how-tos/configure-azure-key-vaults-as-a-vault-backend-with-vault-entity.md, app/_how-tos/configure-google-cloud-secret-as-a-vault-backend.md, app/_how-tos/configure-hashicorp-vault-as-a-vault-backend.md, app/_how-tos/configure-the-konnect-config-store.md, app/_how-tos/store-a-mistral-api-key-as-a-secret-in-konnect-config-store.md, app/_how-tos/store-keyring-in-hashicorp-vault.md, app/_includes/prereqs/products/konnect.md, app/_layouts/how-to.html
Fixes #461 
* Next steps on all the vault backend docs
* Adjust the Konnect prereq when there is no decK involved - previously it was still using decK env variables even when decK wasn't available. This also removed the need for a second prereq that sets more environment variables
[prereqs for Konnect API without decK](https://deploy-preview-473--kongdeveloper.netlify.app/how-to/configure-the-konnect-config-store/); also see next steps at the bottom
[page that has the decK env variables/instructions](https://deploy-preview-473--kongdeveloper.netlify.app/how-to/configure-hashicorp-vault-as-a-vault-backend/
)
=> Fix: QA for vaults docs

app/_includes/components/entity_params_table.html, app/_plugins/blocks/entity_params_table.rb, app/_plugins/drops/entity_params_table.rb, app/gateway/traffic-control/health-checks-circuit-breakers.md
Block that renders a table with entity params and their description, it pulls the information from gateway/admin-ee API spec (the local file we have in the api-specs folder).
Usage:
```
{% entity_params_table %}
entity: Upstream # This should match the name of the entity in the Schema defined in the api spec
config:
- name: healthchecks.passive.healthy.successes
description: Number of successes in proxied traffic (as defined by `healthchecks.passive.healthy.http_statuses`) to consider a Target healthy, as observed by passive health checks. This needs to be positive when passive checks are enabled so that healthy traffic resets the unhealthy counters.
- name: healthchecks.passive.unhealthy.tcp_failures
description: Number of TCP failures in proxied traffic to consider a Target unhealthy, …
```
=> Add basic {% entity_params_table %}

app/_how-tos/allow-multiple-authentication.md, app/_includes/how-tos/validations/request-check/index.html, app/_includes/how-tos/validations/request-check/snippet.md, tools/track-docs-changes/config/sources.yml
Fixes #401 
I couldn't figure out how to add the `--user` argument for the request check without breaking the output. What am I missing @fabianrbz ?
Also, the [original guide](https://docs.konghq.com/gateway/latest/kong-plugins/authentication/allowing-multiple-authentication-methods/#:~:text=%2D%2Ddata%20%27%7B%22name%22%3A%20%22request%2Dtermination%22%2C%20%22config%22%3A%20%7B%20%22status_code%22%3A%20401%2C%20%22content_type%22%3A%20%22application/json%3B%20charset%3Dutf%2D8%22%2C%20%22body%22%3A%20%22%7B%5C%22error%5C%22%3A%20%5C%22Authentication%20required%5C%22%7D%22%7D%20%7D%27) sets the error message for the Request Termination plugin in the JSON body, but I never got that to work right, so I went with setting it via `config.message` instead. …
=> How-to: multiple plugin auth

app/_includes/components/konnect_roles_table.html, app/_plugins/blocks/konnect_roles_table.rb, app/_plugins/drops/konnect_roles_table.rb, app/konnect/teams-and-roles.md
Add {% konnect_roles_table %} block.
Renders a table with the roles + description of the provided schema
Usage:
Pass the name of the schema as defined in
`api-specs/konnect/identity/vX/openapi.yaml`
The name of the schemas can be found under:
`components.responses.Roles.content.application/json.schema.properties`
```
{% konnect_roles_table %}
schema: audit_logs
{% endkonnect_roles_table %}
```
TODO:
* The following  roles are not defined in the spec
- Networks
-   Service Catalog
-   Portals
-   Application Auth Strategies
-   DCR
* Teams aren't defined in the spec
Related https://github.com/Kong/developer.konghq.com/issues/372
=> Add {% konnect_roles_table %}

app/_includes/sections/data-plane-node-ports.md, app/gateway/cp-dp-communication.md, app/gateway/network-ports-firewall.md, app/konnect/mesh-manager.md, app/konnect/network.md, tools/track-docs-changes/config/sources.yml
Fixes #497 
Source doc: https://docs.konghq.com/konnect/network/
Stub page GH issue: https://github.com/Kong/developer.konghq.com/issues/532
https://deploy-preview-531--kongdeveloper.netlify.app/konnect/network/
- The cluster and telemetry hostnames are different from the source doc. This is because the source is wrong, I verified it here: https://kongstrong.slack.com/archives/C04RXLGNB6K/p1740607033227059 I'll be opening a PR to the docs repo that fixes this.
=> Konnect ports/hostnames

app/_landing_pages/admin-api.yaml, app/gateway/secure-the-admin-api.md, tools/track-docs-changes/config/sources.yml
Fixes #369
- https://deploy-preview-542--kongdeveloper.netlify.app/admin-api/
- https://deploy-preview-542--kongdeveloper.netlify.app/gateway/secure-the-admin-api/
=> Feat: Admin API landing page + security reference

app/_assets/entrypoints/api_spec.js, app/_assets/entrypoints/entity_schema.js, app/_assets/entrypoints/plugin_schema.js, app/_assets/javascripts/apps/APISpec.vue, app/_assets/javascripts/apps/EntitySchema.vue, app/_assets/javascripts/apps/PluginSchema.vue, package-lock.json, package.json
Replace usage of `@kong/spec-renderer-dev` package with `@kong/spec-renderer` (we dropped the dev from the package name in [v1.88.0](https://github.com/Kong/spec-renderer/releases/tag/v1.88.0))
=> feat: use kong spec-renderer v1.88.0 package [KHCP-15445]

package-lock.json, package.json
As part of [v1.89.0](https://github.com/Kong/spec-renderer/releases/tag/v1.89.0) of spec-renderer we've enabled scrolling into view the nested fields that are linked via permalinks.
https://konghq.atlassian.net/browse/KHCP-15281
https://github.com/user-attachments/assets/e1b37143-76d4-4f78-9c32-1cdc97dc681e
=> chore(spec-renderer): bump to v1.89.0 [KHCP-15281]

app/deck/file/manipulation/plugins.md, app/deck/file/manipulation/tags.md, app/plugins.html
Minor edit for demo - need the plugin hub to show up in search better.
=> Chore: plugin page titles +description for search

package-lock.json, package.json
[Diff](https://github.com/Kong/spec-renderer/compare/v1.89.0...v1.90.1)
Major changes:
- replace `h1` tags with `h2` tags ([info](https://github.com/Kong/spec-renderer/pull/544))
- fixed server URL overflow on mobile ([info](https://github.com/Kong/spec-renderer/pull/541))
- sync selected auth scheme in try-it ([info](https://github.com/Kong/spec-renderer/pull/543))
https://github.com/user-attachments/assets/0463d0a4-f9b8-4168-8e72-716b6a2a196a
=> chore(deps): upgrade to spec-renderer v1.90.1

.github/styles/base/Dictionary.txt, app/_includes/upgrade/lts-changes.md, app/gateway/upgrade/lts-upgrade.md, tools/track-docs-changes/config/sources.yml
Fixes #657 
@fabianrbz I noticed that the `{% table %}` block doesn't seem to respect newlines, so I ended up adding `<br><br>` tags everywhere. Is there a way to fix that, or should I leave them in?
https://deploy-preview-963--kongdeveloper.netlify.app/gateway/upgrade/lts-upgrade/
(would this be better as `/gateway/upgrade/28-34-lts` or similar?)
=> Gateway 2.8 > 3.4 LTS upgrade guide

api-specs/gateway/admin-ee/3.10/openapi.yaml, app/_data/kong-conf/3.10.json, app/_data/kong-conf/index.json, app/_data/products/gateway.yml, tools/kong-conf-to-json/index-file.js, tools/kong-conf-to-json/run.js
Bumps latest version to 3.10 so that we can easily see all new docs.
This is what I found needed bumping:
* Plugin toolkit - generated the schemas, examples, and data files
* kong.conf - ran the conf tool at tools/kong-conf-to-json
* copied over the 3.10 admin api spec
* new product version in site.data.products.gateway
Issues/questions:
* Should we retire the plugin examples from the docs-plugin-toolkit? We won't need them for the dev site, so maybe I didn't need to generate 3.11
* When generating kong.conf, passing `3.10` made the tool read it as `3.1`, so it generated `3.1.json`. Not a big deal, but something to look out for:
```
node run --file=../../kong.conf.default --version=3.10
kong.conf file in json format written to ../../app/_data/kong-conf/3.1.json.
```
=> chore: Bump latest gateway version to 3.10

app/gateway/breaking-changes.md, tools/track-docs-changes/config/sources.yml
Fixes #631 
Fixes #997
Migrated the 3.10 breaking changes and added subheaders for patches.
From issue 631:
> All h3 and lower headers turned into bold text for the sake of migration. We'll need to come up with a better solution for how to format this page so it's easy to navigate to each release but still somehow maintain the headers in each section.
There's a surprising number of patch versions with breaking changes, so I gave them h3s, and then each breaking change can have an h4, so it doesn't show up in the right nav. @cloudjumpercat @fabianrbz what do you think of this approach?
https://deploy-preview-998--kongdeveloper.netlify.app/gateway/breaking-changes/
=> Gateway 3.10 breaking changes

app/_kong_plugins/jwt/examples/verified-claim.yaml, app/_plugins/filters/liquify.rb
The `liquify` filter needs access to the `site` context to be able to find the `markdownify` filter
=> Fix liquid rendering

app/_data/entity_examples/config.yml, app/_gateway_entities/partial.md, app/_landing_pages/gateway/entities.yaml, tools/track-docs-changes/config/sources.yml
Fixes #1016 
- I got rid of the OSS/Enterprise references from the original docs but I'm wondering if it's clear enough. I think there could be some confusion about which partial type is supported by different plugins. It might be helpful to include that in the plugin pages.
- I think the [API spec](https://docs.konghq.com/gateway/api/admin-ee/latest/#/schemas/Partial) could use the specific redis-ce and redis-ee schemas (with oneOf under config)
=> Feat: Partials entity

app/_how-tos/configure-oidc-with-introspection.md, app/_kong_plugins/openid-connect/examples/introspection-auth.yaml, tools/track-docs-changes/config/sources.yml
Fixes #1142 
The includes and the Keycloak prereq depend on https://github.com/Kong/developer.konghq.com/pull/1196.
https://deploy-preview-1201--kongdeveloper.netlify.app/plugins/openid-connect/examples/introspection-auth/ 
https://deploy-preview-1201--kongdeveloper.netlify.app/how-to/configure-oidc-with-introspection/
=> OIDC with introspection auth

app/gateway/traditional-mode.md
Fixes #567 
https://deploy-preview-1206--kongdeveloper.netlify.app/gateway/traditional-mode/#about-kong-gateway-clusters
I added the remaining section from the existing [Clustering reference](https://docs.konghq.com/gateway/latest/production/clustering/) to the traditional mode page (which is where the rest of the clustering info went).
=> fix: Traditional mode clustering info

app/_how-tos/configure-oidc-with-auth-code-flow.md, app/_kong_plugins/openid-connect/examples/authorization-code.yaml, tools/track-docs-changes/config/sources.yml
Fixes #1150 
Note that I purpose didn't include `authorization_endpoint` in the plugin example, even though it's in the how-to. That setting is necessary because the how-to uses Docker.
https://deploy-preview-1224--kongdeveloper.netlify.app/how-to/configure-oidc-with-auth-code-flow/
https://deploy-preview-1224--kongdeveloper.netlify.app/plugins/openid-connect/examples/authorization-code/
=> OIDC auth code flow

app/_includes/components/entity_example/format/snippets/admin-api.md, app/_includes/components/entity_example/format/snippets/konnect-api.md, app/_kong_plugins/openid-connect/examples/amazon-cognito.yaml, app/_kong_plugins/openid-connect/examples/auth0.yaml, app/_kong_plugins/openid-connect/examples/azure-ad.yaml, app/_kong_plugins/openid-connect/examples/cert-bound-access-tokens.yaml, app/_kong_plugins/openid-connect/examples/curity.yaml, app/_kong_plugins/openid-connect/examples/dpop.yaml, app/_kong_plugins/openid-connect/examples/google.yaml, app/_kong_plugins/openid-connect/examples/mtls-client-auth.yaml, app/_kong_plugins/openid-connect/examples/okta.yaml, app/_kong_plugins/openid-connect/index.md, tools/track-docs-changes/config/sources.yml
This fixes all the remaining untested OIDC examples and adds info about cert-bound access tokens and DPoP to the OIDC doc.
Not attached to a specific issue #, trying to unblock us for QA.
=> OIDC: client auth + 3rd party examples

app/_how-tos/set-up-dynatrace-with-otel.md
We've gotten many complaints and confusion around treating dynatrace as a plugin, and it's caused our users a lot of grief. Since the premium partners page exists now, we no longer need to have dynatrace exposed in this fake way.
=> Chore: Remove plugin metadata from dynatrace guide

app/_how-tos/configure-the-konnect-config-store.md, app/_how-tos/store-a-mistral-api-key-as-a-secret-in-konnect-config-store.md, app/_includes/prereqs/konnect-api-for-curl.md
Fixes #971 
- https://deploy-preview-1233--kongdeveloper.netlify.app/how-to/store-a-mistral-api-key-as-a-secret-in-konnect-config-store/
- https://deploy-preview-1233--kongdeveloper.netlify.app/how-to/configure-the-konnect-config-store/
=> fix: Config Store how tos

app/_indices/kubernetes-ingress-controller.yaml, app/kubernetes-ingress-controller/license.md, tools/track-docs-changes/config/sources.yml
Resolves #722
This might be two how-tos in the future, but this works for now
[/kubernetes-ingress-controller/license/](https://deploy-preview-1249--kongdeveloper.netlify.app/kubernetes-ingress-controller/license/)
=> Add KIC license page

.github/styles/base/Dictionary.txt, app/kubernetes-ingress-controller/faq/migrate-ingress-to-gateway.md, app/kubernetes-ingress-controller/migrate/credential-kongcredtype-label.md, app/kubernetes-ingress-controller/migrate/ingress-to-gateway.md, app/kubernetes-ingress-controller/migrate/kongingress.md, tools/track-docs-changes/config/sources.yml
Resolves #750
Resolves #751
Resolves #752
[/kubernetes-ingress-controller/migrate/credential-kongcredtype-label/](https://deploy-preview-1278--kongdeveloper.netlify.app/kubernetes-ingress-controller/migrate/credential-kongcredtype-label/)
[/kubernetes-ingress-controller/migrate/ingress-to-gateway/](https://deploy-preview-1278--kongdeveloper.netlify.app/kubernetes-ingress-controller/migrate/ingress-to-gateway/)
[/kubernetes-ingress-controller/migrate/kongingress/](https://deploy-preview-1278--kongdeveloper.netlify.app/kubernetes-ingress-controller/migrate/kongingress/)
=> KIC Migration guides

app/_indices/kubernetes-ingress-controller.yaml, app/kubernetes-ingress-controller/reference/secrets-in-plugins.md, tools/track-docs-changes/config/sources.yml
Fixes #748 
[/kubernetes-ingress-controller/reference/secrets-in-plugins/](https://deploy-preview-1311--kongdeveloper.netlify.app/kubernetes-ingress-controller/reference/secrets-in-plugins/)
=> KIC plugin secrets

app/_plugins/generators/indices.rb
Sample config:
```yaml
sections:
- items:
- type: how-to-search
title: Demo Search
description: This is a long description
tags: 
- demo
products:
- operator
```
=> Add support for how-to-search on indices

.github/styles/frontmatter/Keys.txt, app/_assets/stylesheets/index.css, app/_kong_plugins/ai-azure-content-safety/index.md, app/_kong_plugins/ai-proxy-advanced/index.md, app/_kong_plugins/ai-rag-injector/index.md, app/_kong_plugins/ai-rate-limiting-advanced/index.md, app/_kong_plugins/ai-sanitizer/index.md, app/_kong_plugins/ai-semantic-cache/index.md, app/_kong_plugins/ai-semantic-prompt-guard/index.md, app/_layouts/plugins/with_aside.html
Fixes #1338 
Request from AI Gateway team + sales. Adding a banner that labels AI Gateway Enterprise plugins.
Originally I tried adding a badge as well, but it really looked like overkill - and since we don't use badges for Enterprise, it really stood out as out of place.
=> Ai gateway tiers

app/_indices/operator.yaml, app/operator/konnect/kongpluginbinding.md, app/operator/konnect/labelling.md, app/operator/konnect/reconciliation-loop.md, app/operator/konnect/reference/crds.md, app/operator/konnect/reference/faq.md, app/operator/konnect/troubleshooting/status.md
I'll add preview links later today
https://deploy-preview-1385--kongdeveloper.netlify.app/operator/konnect/reconciliation-loop/
https://deploy-preview-1385--kongdeveloper.netlify.app/operator/konnect/labelling/
https://deploy-preview-1385--kongdeveloper.netlify.app/operator/konnect/reference/faq/
https://deploy-preview-1385--kongdeveloper.netlify.app/operator/konnect/troubleshooting/status/
These items have todo's
https://deploy-preview-1385--kongdeveloper.netlify.app/operator/konnect/kongpluginbinding/
https://deploy-preview-1385--kongdeveloper.netlify.app/operator/konnect/crd/cloud-gateways/configuration/
Fixes #issue
=> Add KGO Konnect reference docs

app/_how-tos/configure-aws-secrets-manager-as-a-vault-backend-with-vault-entity.md
This was the last remaining Gateway Vault how to that didn't have Konnect instructions, so I added them.
Fixes #569
https://deploy-preview-1450--kongdeveloper.netlify.app/how-to/configure-aws-secrets-manager-as-a-vault-backend-with-vault-entity/
=> fix: Make AWS vault how to work on Konnect

app/kubernetes-ingress-controller/migrate/ingress-to-gateway.md
=> Missing breadcrumb in kic doc

app/_how-tos/visualize-ai-gateway-metrics-with-kibana.md
Just happened to notice this one as it's the first how to in the Gateway list, but I searched for `## 1.` to make sure there were no other how tos with manual numbering.
=> fix: Numbered steps on how to

app/_includes/landing_pages/header.md
Prevent the all doc link from being rendered in h2s, e.g. https://developer.konghq.com/operator/#konnect-crds
=> Render `all doc link` in h1 only

app/_how-tos/deck-get-started.md
The decK get started had content before the h2 that wasn't being rendered, so I moved it to the TL;DR.
https://kongstrong.slack.com/archives/GN9V02K4N/p1747081825629909
=> fix: TL;DR in decK get started

app/konnect-platform/account.md
Fixed the link to the pricing page since it was currently a 404.
https://kongstrong.slack.com/archives/CDSTDSG9J/p1747126054849879
https://deploy-preview-1475--kongdeveloper.netlify.app/konnect-platform/account/#how-do-i-manage-and-view-billing-and-usage
=> fix: Konnect billing dashboard link

app/_includes/indices.html
Render the plugin example's title in indices instead of the plugin's name
=> Render the plugin example's title in indices

app/_plugins/generators/indices.rb
Pages need to have relative_path set not only for site re-generation but for the edit link too.
[ai gateway index](https://deploy-preview-1483--kongdeveloper.netlify.app/index/ai-gateway/)
=> Fix edit link for indices

app/_includes/breadcrumbs.html, app/_includes/breadcrumbs_and_links.html, app/_includes/get_help.html, app/_layouts/api/spec.html, app/_layouts/default.html, app/_plugins/generators/explorer.rb, app/_plugins/generators/indices.rb, app/_plugins/generators/mesh.rb, app/_plugins/generators/mesh_policy/generator.rb, app/_plugins/generators/plugins/generator.rb, app/_plugins/generators/references/auto_generated/generator.rb, jekyll-dev.yml
Add support for skipping specific generators locally to speed up local builds.
Cold start is still an issue but edits are fast, there are still a lot of tweaks we can do like disabling api specs and how-tos but those require more work, I'll get to them eventually, but for now I wanted to unblock the team.
With the new changes:
https://github.com/user-attachments/assets/e26a3884-7e45-4fe8-b3a9-491521eb1635
Without the changes, same edit:
There's a new section in jekyll-dev.yml, you can uncomment the section and the generators you don't need.
```yaml
```
=> Local perf improvements

app/_includes/components/kong_conf.html, app/_includes/indices.html, app/_includes/upgrade/lts-changes.md, app/_plugins/hooks/post_process_html.rb, app/gateway/plugins/datakit.md, app/gateway/traditional-mode.md, tools/track-docs-changes/config/missing_dev_site_url.yml
Fix links to kong.conf sections and update references
Skip processing a heading's id attribute based on
data-skip-process-heading-id=true.
Update the indices to use it too, since they were an exception too.
Added `-section` to the kong.conf section headings, `vaults` was both a section and a param causing the original issue because both ended up having the same id.
I also updated all the links
=> Fix links to kong.conf sections and update references

app/_plugins/generators/site_data.rb
=> Don't render KIC as a tool in the search/how-tos filter

tools/broken-link-checker/config/ignored_placeholder_paths.json
Remove placeholder_paths, they were set in the early stages of the project to preven the broken links check from failing.
=> Remove ignored_placeholder_paths from broken links

app/_kong_plugins/ai-rag-injector/examples/openai-redis.yaml
Fixes incorrect config sample for the RAG injector plugin.
https://deploy-preview-1501--kongdeveloper.netlify.app/plugins/ai-rag-injector/examples/openai-redis/
=> fix: Fix incorrect config sample for RAG injector

.github/workflows/check-links-scheduled.yml, app/_plugins/hooks/after_init.rb, netlify.toml
Fixes the scheduled broken link checker
Fixes #1543 
I ran the job on this branch:
https://github.com/Kong/developer.konghq.com/actions/runs/15156292480/job/42611824743
=> Don't skip generators if JEKYLL_ENV=test

.github/styles/base/Dictionary.txt, .github/styles/frontmatter/Keys.txt, app/_kong_plugins/openid-connect/examples/acl-auth.yaml, app/_kong_plugins/openid-connect/examples/amazon-cognito.yaml, app/_kong_plugins/openid-connect/examples/auth0.yaml, app/_kong_plugins/openid-connect/examples/authorization-code.yaml, app/_kong_plugins/openid-connect/examples/azure-ad.yaml, app/_kong_plugins/openid-connect/examples/cert-bound-access-tokens.yaml, app/_kong_plugins/openid-connect/examples/claims-based-auth.yaml, app/_kong_plugins/openid-connect/examples/client-credentials.yaml, app/_kong_plugins/openid-connect/examples/consumer-auth.yaml, app/_kong_plugins/openid-connect/examples/curity.yaml, app/_kong_plugins/openid-connect/examples/dpop.yaml, app/_kong_plugins/openid-connect/examples/google.yaml, app/_kong_plugins/openid-connect/examples/headers.yaml, app/_kong_plugins/openid-connect/examples/introspection-auth.yaml, app/_kong_plugins/openid-connect/examples/jwt-access-token.yaml, app/_kong_plugins/openid-connect/examples/kong-oauth-token.yaml, app/_kong_plugins/openid-connect/examples/logout.yaml, app/_kong_plugins/openid-connect/examples/mtls-client-auth.yaml, app/_kong_plugins/openid-connect/examples/okta.yaml, app/_kong_plugins/openid-connect/examples/password.yaml, app/_kong_plugins/openid-connect/examples/refresh-token.yaml, app/_kong_plugins/openid-connect/examples/session-auth.yaml, app/_kong_plugins/openid-connect/examples/user-info-auth.yaml, app/_kong_plugins/openid-connect/index.md, app/_layouts/plugins/example.html
Use the new grouping functionality to organize the OIDC plugin examples.
https://deploy-preview-1579--kongdeveloper.netlify.app/plugins/openid-connect/examples/
@fabianrbz is there a way to disable the "basic use cases" section if all plugin examples are grouped in some way?
=> Organize OIDC examples

app/_how-tos/kic-external-service.md, app/_how-tos/kic-get-started-services-routes.md, app/_how-tos/kic-observability-prometheus-grafana.md, app/_how-tos/kic-plugin-authentication.md, app/_how-tos/kic-plugin-custom.md, app/_how-tos/kic-plugin-degraphql.md, app/_how-tos/kic-proxy-http.md, app/_how-tos/kic-proxy-https.md, app/_how-tos/kic-verify-upstream-tls.md, app/_includes/prereqs/kubernetes/keycloak.md, app/_landing_pages/mesh.yaml, app/mesh/production-usage-values.md, app/mesh/provenance-verification-binaries.md
Fixes #1248 
Didn't remove tags in the following places:
* Mesh policy docs: we have automation to redirect those URLs, so nothing is broken.
* Inso CLI reference: same as above, and this doc is completely generated. Nothing is broken.
Note on the K8s example includes: `release=page.release` wasn't referencing anything that exists in the example include, so it shouldn't break anything.
=> Remove legacy tags

app/_assets/javascripts/apps/APISpec.vue, app/_includes/breadcrumbs.html, app/_layouts/api/spec.html
Fixes https://github.com/Kong/developer.konghq.com/issues/1583
=> Make breadcrumbs sticky on api pages

app/konnect-platform/active-tracing.md
Added notes around supporting Self-Managed, Dedicated, and Serverless Gateways only at the moment to avoid confusing customers who expect this to be available no matter what type of Gateway they deploy.
Relates to support case #00058009 and relevant [Slack thread](https://kongstrong.slack.com/archives/CDSTDSG9J/p1747930618868659).
=> [Fix] Added limitations of Active Tracing to certain Gateway types

app/konnect-platform/network.md
From Slack: https://kongstrong.slack.com/archives/C03ARNUTR1N/p1747753819477109
Realized this was missing from the dev site and it the docs site link was coming up a bit in Slack, so I've added it to the dev site.
=> fix: Add missing regional IP address hostnames link as an FAQ

app/_gateway_entities/admin.md, app/_gateway_entities/rbac.md, app/_how-tos/configure-rbac-user-in-kong-gateway.md, app/_how-tos/create-a-super-admin.md, app/_how-tos/enable-rbac-with-admin-api.md, app/_includes/entities/permissions-table.md, app/_includes/prereqs/enable-rbac.md, tools/track-docs-changes/config/missing_dev_site_url.yml, tools/track-docs-changes/config/sources.yml
Fixes #1035 
Fixes #1037 
Fixes #1038 
Fixes #1036 
For the how-to: the last validation step still uses the admin API, even though it _could_ use decK. I thought that better illustrates the point that the API permissions are working, whereas using decK slightly abstracts that away.
~to do: sources.yaml and index page updates~ 
https://deploy-preview-1563--kongdeveloper.netlify.app/how-to/configure-rbac-user-in-kong-gateway/
https://deploy-preview-1563--kongdeveloper.netlify.app/gateway/entities/rbac/
https://deploy-preview-1563--kongdeveloper.netlify.app/gateway/entities/admins/
=> Kong Manager RBAC docs

app/_redirects
The permalink was changed [here](https://github.com/Kong/developer.konghq.com/pull/1481/files#diff-2ae466d569c6e680e7448a3ed0815a4c8934deb80b55b69ff1d0a7bf019dd522R7) but we didn't add a redirect.
We'll need to a check for this.
=> Add missing redirect for knep get started

app/gateway/traffic-control/health-check-probes.md, app/gateway/traffic-control/health-checks-circuit-breakers.md, tools/track-docs-changes/config/sources.yml
Fixes #1509 
https://deploy-preview-1585--kongdeveloper.netlify.app/gateway/traffic-control/health-check-probes/
Redirect PR here: 
https://github.com/Kong/docs.konghq.com/pull/8801
=> Feat: health check probes

app/_data/products/gateway.yml, app/gateway/changelog.md, app/operator/changelog.md
Chore PR to migrate the 3.10.0.2 changelog for the release that went out last week.
https://deploy-preview-1622--kongdeveloper.netlify.app/gateway/changelog/
=> Chore: Migrate 3.10.0.2 changelog

app/gateway/db-less-mode.md, tools/track-docs-changes/config/sources.yml
Fixes #1510 
No need to update the redirects file on docs, the source page already links to the right place.
https://deploy-preview-1645--kongdeveloper.netlify.app/gateway/db-less-mode/#generate-a-declarative-configuration-file
=> Migrate declarative config doc

app/gateway/network/index.md
I wasn't able to find Gateway ports in site search at all. 
This page title is also misleading, as the whole page is just about ports.
=> Fix: Kong Gateway ports reference

app/_includes/components/plugin_config_example.html, app/_includes/plugins/example.md, app/_plugins/hooks/sections/base.rb
=> Align dropdowns to the title on plugin examples

app/dev-portal/apis.md
Invalid OAS specs are now permitted. Validation methodology is explained to assist users in resolving validation errors locally. Additionally, `validation_messages` are persisted to aid users in resolution. The validation status and messages are surfaced in the UX, but as most users are automating the API catalog, there is a DX-focus in docs.
Fixes #issue
TDX-5484
=> Invalid OAS specs

app/_includes/components/plugin_config_example.html
=> Fix plugin examples so that they rendere correctly when the dropdowns

app/_includes/plugins/ai-proxy/formats.md
Deletes incorrect `extra_body` param from the Bedrock Guardrail sample request.
=> fix: sample bedrock guardrail request

app/_data/products/gateway.yml, app/_how-tos/kic-install.md, jekyll.yml
Bump gateway version for release that came out today: https://github.com/Kong/kong/releases/tag/3.9.1
=> Release: Gateway OSS 3.9.1

app/_landing_pages/custom-plugins.yaml, app/custom-plugins/installation-and-distribution.md, app/custom-plugins/konnect-hybrid-mode.md, app/custom-plugins/reference.md, tools/track-docs-changes/config/sources.yml
Fixes #1635 
Fixes #1631 
Future improvement: We might want a how-to uploading a custom plugin to konnect > adding it to a data plane > applying the plugin.
For the external PDKs, I only added links to the PDK docs/repos and to their plugin examples/templates. 
Should we/do we want to maintain full references for these PDKs on the dev site? For instance, should this page go to the dev site: https://docs.konghq.com/gateway/latest/plugin-development/pluginserver/go/ - or should it live in its own PDK doc?
https://deploy-preview-1705--kongdeveloper.netlify.app/custom-plugins/
https://deploy-preview-1705--kongdeveloper.netlify.app/custom-plugins/konnect-hybrid-mode/
=> Custom plugins in konnect and external PDK links

app/gateway/performance/optimize.md, tools/track-docs-changes/config/sources.yml
Migrate https://docs.konghq.com/gateway/latest/production/performance/brotli/. Missed this page in the overall performance doc migration.
=> Migrate brotli doc

app/_how-tos/configure-aws-secrets-manager-as-a-vault-backend-with-vault-entity.md, app/_how-tos/configure-azure-key-vaults-as-a-vault-backend-with-vault-entity.md, app/_how-tos/configure-google-cloud-secret-as-a-vault-backend.md, app/_how-tos/rotate-secrets-in-google-cloud-secret.md, app/_how-tos/set-up-dynatrace-with-otel.md, app/_how-tos/set-up-jaeger-with-otel.md, app/_includes/components/prereqs.html, app/_includes/prereqs/products/konnect.md
When we added the new DP creation method for Konnect, it broke how tos that required you to pass in en var to the data plane (or at least users could no longer copy/paste down the page). This adds support for passing the env var in when the DP is created for Konnect.
**Important for reviewers:** I retested all of these how tos with Konnect, except Azure since it's not published due to authentication problems. GCP env var are in 1Pass as well as the Mistral API key and Dynatrace. 
- https://deploy-preview-1731--kongdeveloper.netlify.app/how-to/rotate-secrets-in-google-cloud-secret/
- https://deploy-preview-1731--kongdeveloper.netlify.app/how-to/configure-google-cloud-secret-as-a-vault-backend/
- https://deploy-preview-1731--kongdeveloper.netlify.app/how-to/configure-aws-secrets-manager-as-a …
=> fix: Konnect DP creation with env var

app/_how-tos/kic-proxy-tcp-sni.md
Fixes incorrect route name in the Proxy TCP traffic over TLS by SNI guide
https://deploy-preview-1741--kongdeveloper.netlify.app/kubernetes-ingress-controller/routing/tcp-by-sni/
=> fix: KIC proxy TCP SNI route name

app/_plugins/generators/plugins/pages/overview.rb, app/_plugins/generators/plugins/plugin.rb, app/_plugins/tags/if_version.rb
Setting `RENDER_IF_VERSION_UNRELEASED=true` when running the docs makes `if_version` to 
render the content if the version hasn't been released (locally and preview-apps only)
=> If version plugin pages

app/_gateway_entities/vault.md
https://github.com/Kong/kong-ee/pull/12244 added a new config option to all vaults: `base64_decode`. 
Fixes #issue
=> Add base64_decode option to vaults

app/_landing_pages/konnect-api.yaml
Small edit from Slack report: https://kongstrong.slack.com/archives/CDSTDSG9J/p1750790797074599?thread_ts=1750714733.115429&cid=CDSTDSG9J
User expected to see this page marked as Konnect Platform and didn't click on it because they thought it wasn't what they were looking for.
=> Add konnect-platform as product for konnect-api

app/_plugins/hooks/sections/how-to.rb
The problem was that the code was setting data-deployment-topology even if the topology was empty.
Fixes #issue
=> Don't swallow content before steps in how-tos

app/konnect-platform/account.md
Missing info reported on slack. 
This was yet another page we didn't migrate because it doesn't need to exist on its own, but now there's no information about this feature anywhere on the site, which makes it look like it doesn't exist.
Merge redirect PR after this one: https://github.com/Kong/docs.konghq.com/pull/8872
https://deploy-preview-1957--kongdeveloper.netlify.app/konnect-platform/account/#org-switcher
=> Migrate org switcher info

app/gateway/breaking-changes.md
Document breaking changes for Gateway 3.11.
The AI plugins breaking change is from the changelog; the wasm one _should_ be in the changelog but isn't. Will keep an eye on the changelog when eng works on it.
=> Chore: breaking changes in Gateway 3.11

app/_gateway_entities/key-set.md, app/deck/reference/entities.md
Mark keys and key sets as supported by decK.
The Keys entity page already has decK as a tool option, so that doesn't need updating. 
I didn't put a decK version or new_in since we're avoiding mentioning versions in the decK docs.
=> Mark Keys/Key sets as supported in decK

app/_assets/javascripts/how_to.js, app/_assets/stylesheets/index.css, app/_data/schemas/frontmatter/how_to.json, app/_data/series.yml, app/_how-tos/gateway-install-helm-konnect.md, app/_how-tos/gateway-install-helm-onprem-admin-api.md, app/_how-tos/gateway-install-helm-onprem-manager.md, app/_how-tos/gateway-install-helm-onprem.md, app/_includes/info_box/sections/series.html, app/_includes/k8s/cloud-ingress-controller-create-ingress.md, app/_includes/k8s/cloud-ingress-controller-install-tabs.md, app/_includes/k8s/cloud-ingress-controller-single-ingress.md, app/_includes/k8s/cloud/aks/annotations.md, app/_includes/k8s/cloud/aks/install.md, app/_includes/k8s/cloud/aks/test-with-public-lb.md, app/_includes/k8s/cloud/eks/annotations.md, app/_includes/k8s/cloud/eks/install.md, app/_includes/k8s/cloud/eks/test-with-public-lb.md, app/_includes/k8s/cloud/gke/annotations.md, app/_includes/k8s/cloud/gke/install.md, app/_includes/k8s/cloud/gke/test-with-public-lb.md, app/_includes/k8s/cloud/kic/annotations.md, app/_includes/k8s/cloud/kic/install.md, app/_includes/k8s/cloud/kic/test-with-public-lb.md, app/_includes/k8s/helm-ingress-setup.md, app/_includes/sections/prev_next.html, app/_layouts/how-to.html, app/_plugins/generators/data/breadcrumbs.rb, app/_plugins/generators/data/series.rb
Adds on-prem Kubernetes install instructions that didn't make the migration deadline.
I also made a few small platform changes:
* Series can now define a `breadcrumb_title`. If set, it's automatically added as the last breadcrumb item
* `short_title` is used for the next/prev links on how-tos
* `tldr` can be null (they don't make sense in some series)  
[/gateway/install/kubernetes/on-prem/](https://deploy-preview-1973--kongdeveloper.netlify.app/gateway/install/kubernetes/on-prem/) + the rest of the series.
I tested the KIC instructions, and am trusting that the cloud annotations haven't changed since the last time I tested.
=> Gateway kubernetes install

app/_landing_pages/gateway/kong-manager.yaml, app/_landing_pages/gateway/openid-connect.yaml, app/gateway/kong-manager/openid-connect.md
Fixes #1033 
Fixes #1031 
Fixes #1034
To do: make a ticket to write how-tos for enabling OIDC and setting up auth group mapping. I couldn't get it working properly with keycloak; opening this as a reference in the interest of time + user requests.
tiles:
https://deploy-preview-1987--kongdeveloper.netlify.app/gateway/kong-manager/#kong-manager-authentication
https://deploy-preview-1987--kongdeveloper.netlify.app/gateway/openid-connect/#references
new page:
https://deploy-preview-1987--kongdeveloper.netlify.app/gateway/kong-manager/openid-connect/
=> Migrate kong manager OIDC references

app/_how-tos/deck-get-started.md
Fixes #1883 
Moved the step up after the Service step instead of removing. The feedback in the linked issue was missing a key piece:
"Would expect to see deck dump after creating a service to see the value in there"
=> Move deck dump step up in getting started guide

app/gateway/performance/benchmarks.md
Update public benchmar perf tests for `3.11.0.0-rc.8`
The raw results could be found [here](https://docs.google.com/spreadsheets/d/1knu87tczpuTQ4a5si3WSkOoFHWf0pS8vqNpC44-Oxmw/edit?gid=1180371825#gid=1180371825)
https://deploy-preview-2003--kongdeveloper.netlify.app/gateway/performance/benchmarks/
=> - Update public benchmar perf tests for 3.11.0.0-rc.8

app/gateway-manager/control-plane-groups.md
Added a missing conflict for `consumer` entities. The table showed other entity conflict types (control plane group names, consumer groups, credentials, etc.) but not one for just consumers.
Fixes support case #00059261.
=> [fix] Add missing conflict for `consumer` entities in Konnect control plane groups.

app/_includes/prereqs/auth/oidc/keycloak-password.md
Automated testing caught an issue with Keycloak. Turns out they recently updated their port mapping requirements, and the old config wasn't working: https://github.com/keycloak/keycloak/commit/a74b60199be923c70e0b70fd53cebbf173c7a1a4
=> Fix: Keycloak prereq

app/_data/products/gateway.yml
Extended the EOL of Amazon Linux 2 on Kong Gateway 3.4 and 3.10 LTS releases to June 2026.
Related: https://old-docs-preview--kongdocs.netlify.app/gateway/latest/support-policy/#sunset-support
=> Fix: EOL June 2026 for Amazon Linux 2 for LTS releases.

app/_event_gateway_policies/schema-validation.md
Fixes invalid example of schema validation for KNEP.
https://deploy-preview-2079--kongdeveloper.netlify.app/event-gateway/policies/schema-validation/
=> fix schema validation example for knep

app/_event_gateway_policies/decrypt.md, app/_event_gateway_policies/encrypt.md, app/_event_gateway_policies/modify-headers.md, app/_event_gateway_policies/schema-validation.md
Move schemas below examples. The current positioning puts the schemas out of context and makes examples easy to miss, plus the schema takes a second to load and makes the page jump.
=> Fix: Event Gateway policies layout

app/_includes/components/operator_podtemplatespec_example.md, app/_plugins/blocks/operator_podtemplatespec_example.rb, app/_plugins/utils/hash_to_yaml.rb
Fixes https://github.com/Kong/developer.konghq.com/issues/1457
=> Remove extra spacing in {% operator_podtemplatespec_example %}

jekyll-dev.yml
It should speed up local build times
=> Exclude app/_references in dev

app/dev-portal/custom-domains.md
We had a support case where the Dev Portal names was no longer occurring because the SSL cert expired, and it expired because the DNS records were made private and not publicly seen which meant the ACME challenge for the SSL certificate was not able to pass the validation checks. Currently, the CNAME and CAA DNS records must be public so Konnect can resolve them.
Support case #00059223.
=> Fix: Clarify that DNS records must be public.

app/_how-tos/configure-oidc-with-auth-code-flow.md, app/_how-tos/configure-oidc-with-client-credentials.md, app/_kong_plugins/openid-connect/examples/extra-jwks.yaml, app/_kong_plugins/openid-connect/index.md
Fixes #1198 
Fixes #1073 
A bunch of OIDC doc improvements from Slack and support cases.
* Token validation for multiple IdPs: This was originally going to be an FAQ but made more sense as an example, so I did both.
* Added the auth code and client credentials FAQs to both the plugin index and the relevant how-to docs.
https://deploy-preview-2112--kongdeveloper.netlify.app/plugins/openid-connect/#claims-based-authorization
https://deploy-preview-2112--kongdeveloper.netlify.app/plugins/openid-connect/#faqs
https://deploy-preview-2112--kongdeveloper.netlify.app/plugins/openid-connect/examples/extra-jwks/
https://deploy-preview-2112--kongdeveloper.netlify.app/how-to/configure-oidc-with-auth-code-flow/#faqs
https://deploy-preview-2112--kongdeveloper.netlify.app/how-to/configure-oidc-with-clien …
=> OIDC FAQs and example for multiple IdP auth

.github/styles/base/Dictionary.txt, app/operator/konnect/control-plane-watch-namespaces.md, app/operator/reference/custom-resources.md
Fixes https://kongstrong.slack.com/archives/CDSTDSG9J/p1751618928264159
Original PR: https://github.com/Kong/docs.konghq.com/pull/8741
- https://deploy-preview-2092--kongdeveloper.netlify.app/operator/konnect/control-plane-watch-namespaces/
- https://deploy-preview-2092--kongdeveloper.netlify.app/operator/reference/custom-resources/#watchnamespacegrant (manually added since we don't have this autogenerated yet)
- https://deploy-preview-2092--kongdeveloper.netlify.app/operator/reference/custom-resources/#watchnamespacegrantspec (manually added since we don't have this autogenerated yet)
- https://deploy-preview-2092--kongdeveloper.netlify.app/operator/reference/custom-resources/#watchnamespacegrantfrom (manually added since we don't have this autogenerated yet)
=> Migrate CP namespace watch guide

.github/styles/frontmatter/Dictionary.txt, app/_gateway_entities/ca-certificate.md, app/_gateway_entities/key-set.md
CA Certificates and Key Sets schema paths changed in the generated spec.
https://deploy-preview-2123--kongdeveloper.netlify.app/gateway/entities/key-set/
https://deploy-preview-2123--kongdeveloper.netlify.app/gateway/entities/ca-certificate/
=> Fix: paths to schemas

app/_gateway_entities/plugin.md
https://kongstrong.slack.com/archives/C03CTMSHP6C/p1752220957298099
https://deploy-preview-2136--kongdeveloper.netlify.app/gateway/entities/plugin/#known-limitations-of-dynamic-plugin-ordering (see the first bullet point, I added Consumer Groups to it)
=> fix: Add Consumer Groups to dynamic plugin ordering limitations

app/_references/gateway/pdk/reference/3.11/kong.request.md
=> Re-generate pdk docs against  3.11 tag

app/ai-gateway/monitor-ai-llm-metrics.md
Adds missing note about exposing LLM cost metric.
=> fix:Add missing note about LLM cost metric

app/_how-tos/automate-api-catalog.md, app/_how-tos/collect-audit-logs.md, app/_how-tos/collect-dev-portal-audit-logs.md, app/_how-tos/configure-the-konnect-config-store.md, app/_how-tos/create-centrally-managed-consumer.md, app/_how-tos/enable-oidc-auth-for-dev-portal.md, app/_how-tos/store-a-mistral-api-key-as-a-secret-in-konnect-config-store.md, app/_includes/prereqs/api-catalog.md, app/_includes/prereqs/dedicated-cloud-gateways.md, app/_includes/prereqs/dev-portal-configure.md, app/_includes/prereqs/publish-api.md, app/contributing/index.md
Fixes https://kongstrong.slack.com/archives/C06TLRHG8KX/p1752491072844909
Changed the Konnect only how tos to use `konnect_api_request` instead of `control_plane_request`. 
**Note:** I did not test the how tos since functionally, all that changed was the control plane URL was hardcoded instead of an env var.
- https://deploy-preview-2183--kongdeveloper.netlify.app/how-to/store-a-mistral-api-key-as-a-secret-in-konnect-config-store/
- https://deploy-preview-2183--kongdeveloper.netlify.app/how-to/enable-oidc-auth-for-dev-portal/
- https://deploy-preview-2183--kongdeveloper.netlify.app/how-to/create-centrally-managed-consumer/
- https://deploy-preview-2183--kongdeveloper.netlify.app/how-to/configure-the-konnect-config-store/
- https://deploy-preview-2183--kongdeveloper.netlify.app/how-to/colle …
=> Fix: Konnect API requests

app/_redirects
Issue reported on slack. Interim fix - can't easily fix directly in source, as this spec is generated somewhere, still tracking that down.
=> fix: Redirects for broken links in API spec

api-specs/plugins/header-cert-auth/openapi.yaml, app/_includes/plugins/manual-consumer-mapping.md, app/deck/reference/entities.md
Fixing issues with the Header Cert Auth plugin:
* decK doesn't support Header Cert Auth credentials, so we can't include decK examples for creating those. 
* The API spec (manually written) was incorrect, checked the credential schema and updated it accordingly 
Issue reported on Slack.
https://deploy-preview-2227--kongdeveloper.netlify.app/plugins/header-cert-auth/#manual-mappings-between-certificate-and-consumer-objects
https://deploy-preview-2227--kongdeveloper.netlify.app/plugins/header-cert-auth/api/
=> Header cert auth plugin fixes

app/gateway/third-party-support.md
Adding a note about support vs maintenance for 3rd party tools for Gateway.
This stems from a concern that someone had about a user assuming that Kong will maintain these tools for them:
> Is there a way to call out that the [third-party supportability](https://developer.konghq.com/gateway/third-party-support/) mentioned here does not mean that Kong will work on upgrading/maintaining the third party tools in a customer's deployment stack?
Reviewers: does this note cover the issue for you?
https://deploy-preview-2252--kongdeveloper.netlify.app/gateway/third-party-support/
=> Third-party tools note

app/_includes/info_box/reference.html, app/operator/konnect/control-plane-watch-namespaces.md
Add minimum version to reference page info boxes
[/operator/konnect/control-plane-watch-namespaces/](https://deploy-preview-2280--kongdeveloper.netlify.app/operator/konnect/control-plane-watch-namespaces/)
=> Add support for min_version in references

app/_gateway_entities/license.md
=> Fix: Incorrect license URL

app/_includes/components/table.html
Fixes this alignment issue, where any table with mismatched cell content length makes it difficult to read the adjoining cells + looks misaligned.
For example:
https://developer.konghq.com/gateway/breaking-changes/#known-issues-in-3-6-0-0
https://deploy-preview-2290--kongdeveloper.netlify.app/gateway/breaking-changes/#known-issues-in-3-6-0-0
Before:
After:
=> Align table text to top of cell

app/_includes/plugins/table.html, app/_plugins/drops/plugins/tabular.rb
Minor adjustment to the plugin compatibility table to also include the plugin name from code, eg "Key Authentication - Encrypted" gets `key-auth-enc`. Based on an AI bot answer where the bot was unable to tell the the Kafka Log plugin was present in this table because the question asked for `kafka-log` (that really should've worked, but for some reason it didn't).
https://deploy-preview-2291--kongdeveloper.netlify.app/plugins/compatibility/
=> Add plugin name in source name format

app/_data/changelogs/gateway.json, app/gateway/breaking-changes.md, tools/changelog-generator/missing_entries/3.10.0.0/amazonlinux-2-brotli.yml, tools/changelog-generator/missing_entries/3.11.0.0/amazonlinux-2-brotli.yml, tools/changelog-generator/missing_entries/3.6.0.0/amazonlinux-2-brotli.yml, tools/changelog-generator/missing_entries/3.7.0.0/amazonlinux-2-brotli.yml, tools/changelog-generator/missing_entries/3.8.0.0/amazonlinux-2-brotli.yml, tools/changelog-generator/missing_entries/3.9.0.0/amazonlinux-2-brotli.yml
Related to https://konghq.atlassian.net/browse/FTI-6834.
While the linked ticket only mentions Amazon Linux 2, you can see which packages are missing the module here: https://github.com/Kong/kong-ee/pull/13409/files
There is no workaround, but they're planning on adding the module back in the next 3.8-3.11 patches.
Also reran the changelog generator to fix some duplicate entries, hopefully that's all fixed properly now.
https://deploy-preview-2307--kongdeveloper.netlify.app/gateway/breaking-changes/
https://deploy-preview-2307--kongdeveloper.netlify.app/gateway/changelog/
=> Gateway 3.x known issue: Missing Brotli module

app/_how-tos/compress-llm-prompts.md
Fixes missing logging params/service name in the prompt compressor how-to.
=> fix: Add missing logging params to the compressor how to

app/_kong_plugins/openid-connect/examples/cert-bound-access-tokens-no-client-info.yaml, app/_kong_plugins/openid-connect/examples/extra-jwks.yaml
Fixes #2247 
* fixing the  `extra_jwks_url` example to remove the extra auth info; it wasn't in the source KB: https://support.konghq.com/support/s/article/Does-the-openid-connect-plugin-support-multiple-IdPs
* Add cert-bound example that uses TLS handshake modifier, from https://tech.aufomm.com/use-oidc-to-secure-kong-manager-and-admins-group-mapping/
https://deploy-preview-2342--kongdeveloper.netlify.app/plugins/openid-connect/examples/cert-bound-access-tokens-no-client-info/
https://deploy-preview-2342--kongdeveloper.netlify.app/plugins/openid-connect/examples/extra-jwks/
=> OIDC plugin examples without client ID or secret

app/_indices/dev-portal.yaml, app/_landing_pages/dev-portal.yaml, app/konnect-platform/audit-logs.md
Fixes #2034
- https://deploy-preview-2368--kongdeveloper.netlify.app/konnect-platform/audit-logs/
- https://deploy-preview-2368--kongdeveloper.netlify.app/index/dev-portal/#overview
- https://deploy-preview-2368--kongdeveloper.netlify.app/dev-portal/#references
_Notes for reviewers:_
- I decided to leave Dev Portal audit log information on the same page as Konnect. They have overlap in a lot of areas as far as docs go, but also, to have a complete picture of Dev Portal, you need the Portal audit logs as well as Konnect org audit logs (see this [Slack](https://kongstrong.slack.com/archives/C02D0BPQC85/p1750284030482209) for details). I've tried to convey this, but maybe the wording needs adjusting.
- What do you think of the "Get Started" green note at the top? I figure this can help users …
=> fix: Dev Portal audit log reference

app/_landing_pages/kubernetes-ingress-controller.yaml
Fixes #1877
https://deploy-preview-2393--kongdeveloper.netlify.app/kubernetes-ingress-controller/
=> fix: Add get started button to KIC landing page

app/_assets/javascripts/apps/PluginSchema.vue
Fixes https://github.com/Kong/developer.konghq.com/issues/2262
Bumped it up to 10 just in case, though if any plugin config goes that deep, that feels like a problem.
The issue was referring to https://developer.konghq.com/plugins/request-callout/reference/
https://deploy-preview-2390--kongdeveloper.netlify.app/plugins/request-callout/reference/#schema--config-callouts-request-http-opts for example
=> fix: bump plugin schema max expanded depth

app/_gateway_entities/plugin.md
Fixes https://github.com/Kong/docs.konghq.com/issues/7988
=> fix: clarify plugin instances

app/gateway/resource-sizing-guidelines.md
Fixes https://kongstrong.slack.com/archives/CDSTDSG9J/p1753967389568559
https://deploy-preview-2405--kongdeveloper.netlify.app/gateway/resource-sizing-guidelines/#in-memory-caching
=> fix: mem_cache_size link in Resource Guidelines

app/_how-tos/docker-compose.md, app/_how-tos/gateway-install-helm-konnect.md, app/_how-tos/gateway-install-helm-onprem-manager.md, app/_how-tos/get-started-with-gateway.md, app/_how-tos/install-gateway-read-only.md, app/_how-tos/operator-get-started-hybrid-create-route.md, app/_how-tos/operator-get-started-kic-create-route.md, app/_how-tos/operator-konnect-getstarted-key-auth.md, app/_landing_pages/admin-api.yaml, app/_landing_pages/konnect-api.yaml, app/_landing_pages/operator/install.yaml, app/_landing_pages/terraform.yaml, app/_layouts/how-to.html, app/gateway/install.md, app/kubernetes-ingress-controller/deployment-topologies/gateway-discovery.md
Fixes #1874
- https://deploy-preview-2408--kongdeveloper.netlify.app/gateway/install/docker/
- https://deploy-preview-2408--kongdeveloper.netlify.app/gateway/install/kubernetes/konnect/
- https://deploy-preview-2408--kongdeveloper.netlify.app/gateway/install/kubernetes/on-prem/manager/
- https://deploy-preview-2408--kongdeveloper.netlify.app/gateway/get-started/
- https://deploy-preview-2408--kongdeveloper.netlify.app/gateway/install/docker-read-only/
- https://deploy-preview-2408--kongdeveloper.netlify.app/operator/dataplanes/get-started/hybrid/create-route/
- https://deploy-preview-2408--kongdeveloper.netlify.app/operator/dataplanes/get-started/kic/create-route/
- https://deploy-preview-2408--kongdeveloper.netlify.app/operator/konnect/get-started/key-authentication/
- …
=> fix: Add "Next steps" to tools, install pages and getting started guide

app/_how-tos/kic-install.md, app/_landing_pages/kubernetes-ingress-controller.yaml
Fixes #2162
- https://deploy-preview-2414--kongdeveloper.netlify.app/kubernetes-ingress-controller/
- https://deploy-preview-2414--kongdeveloper.netlify.app/kubernetes-ingress-controller/install/#faqs
=> fix: Add guidance for managing Kong Gateway with AWS CDK

app/dev-portal/sso.md
Document Portal SSO examples for both custom domains as well as the default domain. Customers were confused by not including default domain examples (e.g. when they are testing out changes in a staging portal)
=> docs: portal sso default domain examples [TDX-6380]

app/_data/support/gateway.yml
3.11 not appearing in compat table
=> Fix: Konnect Gateway compatibility table

docs/publish-api-docs.md, docs/release-checklists.md
Adds instructions on publishing API docs. 
Copies them from our release checklist, and adds a step for updating.
=> Fix: publish api docs internal documentation

app/custom-plugins/schema.lua.md
Fixes incorrect rendering of schema tables:
https://deploy-preview-2480--kongdeveloper.netlify.app/custom-plugins/schema.lua/#schema-lua-specification
=> fix: schema tables rendering

app/custom-plugins/javascript.md
Fixes [#2456](https://github.com/Kong/developer.konghq.com/issues/2456)
https://deploy-preview-2477--kongdeveloper.netlify.app/custom-plugins/javascript/
=> fix: Add konnect note to javascript pdk

app/insomnia/accounts.md, app/insomnia/allowlist.md
Out of [some security/compliance work](https://konghq.atlassian.net/browse/INS-974), we realized there's no warning to make sure that clients should redact any sensitive data before sending us logs or anything else. We're putting this warning in a few spots, training support, etc... but can we make sure that anywhere in the docs we mention reaching out to support that we call out to not include any sensitive data in any requests/responses/logs unless shared securely?
Fixes https://github.com/Kong/developer.konghq.com/issues/2318
=> Fix: Add caution info to Insomnia docs 

app/_kong_plugins/degraphql/index.md
improve degraphql plugin document and fix the errors in the degraphql route examples
=> docs(degraphql-plugin): improve degraphql plugin documentation

app/_includes/how-tos/steps/ping-gateway.md
Added a release variable to always show the most up to date version
Fixes #issue
1. Check that kong gateway... http://localhost:8888/gateway/get-started/#check-that-kong-gateway-is-running
=> fix: add variable to kong gateway guick start version number

app/_data/kuma_to_mesh/config.yaml, app/_indices/mesh.yaml, app/_landing_pages/mesh-manager.yaml, app/assets/icons/migrate.svg, app/index.html, app/mesh-manager/federate-zone.md, app/mesh-manager/migrate-zone.md, app/mesh-manager/service-mesh.md, app/mesh/deploy-kong-mesh-using-terraform-and-konnect.md, app/mesh/import-existing-konnect-kong-mesh-deployment-to-terraform.md
Fixes #1980 
- https://deploy-preview-2549--kongdeveloper.netlify.app/#:~:text=%E2%86%92-,Mesh%20Manager,-Create%2C%20manage%2C%20and (check link for All documentation on the Mesh manager tile)
- https://deploy-preview-2549--kongdeveloper.netlify.app/mesh-manager/#get-started (added more links for get started tiles)
- https://deploy-preview-2549--kongdeveloper.netlify.app/index/mesh/#install-configure (changed name here so it's clearer that this is with Konnect)
- https://deploy-preview-2549--kongdeveloper.netlify.app/mesh/kubernetes/ (If I did it correctly, this page should now be fixed as it was added to the submodule file, was previously missing)
=> fix(mesh-manager): Improve links on landing/index pages from feedback

app/_how-tos/aws-vpc-peering.md, app/_how-tos/gcp-vpc-peering.md, app/_includes/prereqs/dedicated-cloud-gateways.md, app/_landing_pages/dedicated-cloud-gateways.yaml, app/dedicated-cloud-gateways/reference.md
Fixes #2172 
Fixes #2171 
Fixes #2170 (there are no beta labels to remove, so just closing this)
Outstanding questions:
* If you use the API to create a vpc connection on the Konnect side, where do you find the values for `peer-project` and `peer-network`?
Referring to the flags here:
```
gcloud compute networks peerings create $GCP_VPC_PEERING_NAME \
--network=$GCP_VPC_NAME \
--peer-project=? \
--peer-network=? \
--stack-type=IPV4_ONLY \
--import-custom-routes \
--export-custom-routes \
--import-subnet-routes-with-public-ip \
--export-subnet-routes-with-public-ip \
--project=$GCP_PROJECT_ID
```
* The note "Make sure that your VPC ranges don't conflict with the Cloud Gateway Network VPC range." - is this the CIDR range? If not, what does it refer to? …
=> Feat: GCP VPC peering on DCGWs

app/_how-tos/automate-api-catalog-with-terraform.md
According to the konnect-beta Terraform provider version 0.8.0, the `service` is read-only attribute now. It needs to be nested into service_reference to link the API to a gateway service. See https://registry.terraform.io/providers/Kong/konnect-beta/latest/docs/resources/api_implementation
Fixes #issue
https://deploy-preview-2610--kongdeveloper.netlify.app/how-to/automate-api-catalog-with-terraform/
=> fix(dev-portal): Update the API catalog TF how to to use service_reference

app/_indices/kubernetes-ingress-controller.yaml, app/kubernetes-ingress-controller/support.md
* Adding a link to the KIC changelog from the index page
* Support tables:
* Splitting the versions table into supported and unsupported versions
* Adding a note about checking gateway version support
* Minor other cleanup
Issues reported on Slack.
https://deploy-preview-2611--kongdeveloper.netlify.app/kubernetes-ingress-controller/support/
=> fix(kic): Support tables and changelog link

app/_how-tos/get-started-with-mcp.md
Fixes #2503
http://localhost:8888/mcp/kong-mcp/get-started/#configure-claude-desktop
=> fix(ai-gateway): Add instructions for Cursor for using MCP Konnect

app/_gateway_entities/upstream.md, app/_includes/components/entity_example/format/admin-api.md, app/_includes/components/entity_example/format/konnect-api.md, app/_includes/components/entity_example/format/ui.md
Fixing broken and missing links that appear in Gateway entity examples.
Ran into issue when updating L1 menu docs. We have a lot of broken and inconsistently missing links in the entity examples. They don't get caught by the link checker because the API page doesn't 404, it just loads blank.
Also added `konnect-api` as a supported tool for Upstreams, it was missing.
=> fix(gateway/entities): Fix broken links and missing links in Gateway entities

app/_how-tos/create-transit-gateway-with-operator-and-aws.md, app/_how-tos/operator-konnect-control-plane-group.md, app/_how-tos/operator-konnect-control-plane-kic.md, app/_how-tos/operator-konnect-control-plane-mirror.md, app/_how-tos/operator-konnect-control-plane.md, app/_how-tos/operator-konnect-getstarted-controlplane.md, app/_includes/prereqs/operator/konnect_control_plane.md, app/operator/konnect/labelling.md, jekyll.yml
Fixes https://github.com/Kong/kong-operator/issues/1945
* https://deploy-preview-2641--kongdeveloper.netlify.app/operator/konnect/labelling/#labeling
* https://deploy-preview-2641--kongdeveloper.netlify.app/operator/konnect/crd/control-planes/hybrid/#create-a-konnectgatewaycontrolplane
* https://deploy-preview-2641--kongdeveloper.netlify.app/operator/dataplanes/get-started/hybrid/deploy-dataplane/
=> ko: bump KonnectGatewayControlPlane to v1alpha2

app/_indices/service-catalog.yaml, app/_landing_pages/service-catalog.yaml, app/service-catalog/integrations/datadog.md, app/service-catalog/integrations/swaggerhub.md, app/service-catalog/integrations/traceable.md, app/service-catalog/scorecards.md, app/service-catalog/services.md
Fixes #2482 
- https://deploy-preview-2586--kongdeveloper.netlify.app/service-catalog/services/
- https://deploy-preview-2586--kongdeveloper.netlify.app/service-catalog/#explore-key-features
- https://deploy-preview-2586--kongdeveloper.netlify.app/service-catalog/integrations/traceable/
- https://deploy-preview-2586--kongdeveloper.netlify.app/service-catalog/integrations/swaggerhub/
- https://deploy-preview-2586--kongdeveloper.netlify.app/service-catalog/integrations/datadog/
=> feat(service-catalog): Terraform support for integrations and services

app/_landing_pages/konnect.yaml
=> fix: typo in konnect.yaml

app/_includes/upgrade/lts-changes-34-310.md
The text should say "No", but it's displaying an X image:
=> Fix: LTS guide typo

app/deck/file/openapi2kong.md
Fixes #2729 
New feature that went out with decK 1.51. See https://kongstrong.slack.com/archives/C045Y8G7VDW/p1756370528628289 for context.
https://deploy-preview-2735--kongdeveloper.netlify.app/deck/file/openapi2kong/#when-running-deck-file-openapi2kong-i-get-the-error-infinite-circular-reference-detected-how-do-i-resolve-it
=> feat(deck): FAQ for using --ignore-circular-refs with openapi2kong

app/_how-tos/automate-api-catalog-with-terraform.md, app/_how-tos/automate-api-catalog.md, app/dev-portal/apis.md
Origin ticket: https://github.com/Kong/developer.konghq.com/pull/2725#issue-3363654607
> Jobs to be done:
> 
> Why document a plugin that's entirely handled behind the scenes? "for KAA it's more about compliancy and security, to make customers understand that it's injected automatically by konnect to manage authZ."
> DoD:
> 
> Add information about how the KAA plugin is managed / injected in the configuration of the gateway when linking an api to the gateway service here https://developer.konghq.com/dev-portal/apis/#allow-developers-to-consume-your-api
> Add FAQ about it [here](https://developer.konghq.com/how-to/automate-api-catalog/) and [here](https://developer.konghq.com/how-to/automate-api-catalog-with-terraform/)
> Add a search alias for konnect-application-auth to …
=> Fix(dev-portal): Added info about KAA plugin

app/_kong_plugins/cors/index.md
Clarified CORS limitations regarding preflight OPTIONS requests and Host header handling in the plugin documentation.
Fixes #issue
=> Update CORS limitations section in documentation

app/_kong_plugins/kafka-consume/index.md
=> feat(gateway/kafka-consume): add docs on disallowing scope to Service

app/insomnia/enterprise-account-management.md
From:
> Update the enterprise docs to clarify that:
> 
> The activation code can only be used once
> The user who uses the code becomes the owner of the enterprise instance
> The owner can then add other co-owners
> Information
> https://kongstrong.slack.com/archives/C044UFN49RT/p1756386827622849
> 
> Size
> S
Fixes #2726 
- https://deploy-preview-2774--kongdeveloper.netlify.app/insomnia/enterprise-account-management/#enable-enterprise-membership
=> Fix (Insomnia) Clarify activation code for enterprise usage

app/_data/products/gateway.yml
Release checklist item.
Keys are from https://cloudsmith.io/~kong/repos/gateway-312/pub-keys/.
=> chore(gateway): Update GPG and RSA keys for 3.12

app/insomnia/organizations.md
> From:
> Definition of done
> Update the [organization](https://developer.konghq.com/insomnia/organizations/#invite-users-to-your-organization) docs to indicate that invites expire after 30 days
> 
> Information
> https://kongstrong.slack.com/archives/C095TCU8TDX/p1756388045741799
> 
> Size
> S
Fixes #2723 
- Organizations> https://deploy-preview-2770--kongdeveloper.netlify.app/insomnia/organizations/#invite-users-to-your-organization
=> Fix (Insomnia) Clarify invitation expiry time

app/_how-tos/convert-gateway-lts-2.8-3.4.md, app/_how-tos/convert-gateway-lts-3.4-3.10.md, app/_includes/upgrade/lts-upgrade.md, app/deck/file/convert.md, app/deck/reference/3.0-upgrade.md, app/gateway/upgrade/blue-green.md, app/gateway/upgrade/dual-cluster.md, app/gateway/upgrade/in-place.md, app/gateway/upgrade/rolling.md
Fixes #2713 
Reviewers, I'd like your opinion here, as I'm struggling to decide how to structure this content.
Right now, it's like this:
* deck file convert is part of the individual upgrade reference docs (rolling upgrade, in-place upgrade, etc)
* ~the instructions to run it are all in the doc for `deck file convert`. Would this be better as a two how-tos, even if they're exactly the same for 2.8 -> 3.4 as for 3.4 -> 3.10?~ Reworked into how-tos.
https://deploy-preview-2733--kongdeveloper.netlify.app/deck/file/convert/
https://deploy-preview-2733--kongdeveloper.netlify.app/gateway/upgrade/convert-lts-28-34/
https://deploy-preview-2733--kongdeveloper.netlify.app/gateway/upgrade/convert-lts-34-310/
https://deploy-preview-2733--kongdeveloper.netlify.app/deck/reference/3.0-upgrade/
Upgrade …
=> feat(deck): deck file convert for LTS

app/_gateway_entities/vault.md
> Jobs to be done (optional)
> When asked about whether admin_gui_auth_conf and admin_gui_session_conf are referenceable, the AI bot says no, but the correct answer is yes - all values set in kong.conf should be referenceable.
> 
> Definition of done
> Adjust the phrasing of https://developer.konghq.com/gateway/entities/vault/#what-can-be-stored-as-a-secret to say that "all values set in kong .conf are referenceable". For consistency and easy comparability, we should use the same language as the plugin fields section:
> 
> [Referenceable plugin fields](https://developer.konghq.com/gateway/entities/vault/#referenceable-plugin-fields)
> The following plugin fields can be stored and referenced as secrets:
> Information
> n/a
> 
> Due date (optional)
> n/a
> 
> Size
> XS
Fixes #2649
- …
=> Fix (Kong AI): Incorrect answer referenceable vault values

app/_how-tos/get-started-with-datakit.md
One of the APIs used in this guide is no longer functional. 
We could point to something else, but realistically this get started guide is being reworked for 3.12 anyway. Temporarily disabling the test while the guide is being updated so that it doesn't disrupt workflows.
=> Fix: Temporarily disable datakit guide test

app/operator/reference/configuration-options.md
Ensure that `app/operator/reference/configuration-options.md` is in sync with what [was prepared for KO v.2.0.0](https://github.com/Kong/kong-operator/blob/v2.0.0/docs/cli-arguments-for-developer-konghq-com.md)
https://deploy-preview-2832--kongdeveloper.netlify.app/operator/reference/configuration-options/
=> doc(ko): configuration option doc for `v2.0.0`

app/_data/kuma_to_mesh/config.yaml, app/_how-tos/restrict-permissions-to-selected-namespaces-on-kubernetes.md
Fixes #1768 
I'm not sure if this can apply to Konnect too, there's no mention of it in the original doc so I made it on-prem only for now.
https://deploy-preview-2820--kongdeveloper.netlify.app/mesh/restrict-permissions-to-selected-namespaces-on-kubernetes/
=> Feat(Mesh): Restrict permissions to selected namespaces on Kubernetes

app/_assets/entrypoints/application.js, app/_assets/javascripts/components/switch.js, app/_assets/javascripts/how_to.js, app/_assets/stylesheets/index.css, app/_includes/how-tos/controls.html, app/_includes/info_box/concept.html, app/_includes/info_box/sections/controls.html, app/_includes/layouts/aside.html, app/_layouts/how-to.html
Fixes #1880 
Works in the same way as the dropdown, i.e. sets the value in the following order (each option overwrites the previous value):
* user preference stored.
* "?deployment" param in the url.
* if the page has data-topology-switcher="page" updates the url depending on the value of the switch.
* [gateway get-started](https://deploy-preview-2871--kongdeveloper.netlify.app/gateway/get-started/)
* [data-topology-switcher example](https://deploy-preview-2871--kongdeveloper.netlify.app//gateway/install/kubernetes/konnect/)
=> feat: use a toggle switch for the deployment topology

app/_gateway_entities/partial.md
User was confused about Partials, as it wasn't immediately clear that partials are applicable to plugins only. This clarifies that. 
https://github.com/Kong/developer.konghq.com/pull/2836 will help address the confusion as well; it will cover the doc from types onward (which is why I didn't adjust any of that part of the description).
https://deploy-preview-2898--kongdeveloper.netlify.app/gateway/entities/partial/
=> fix(gateway): Clearer description for partials

README.md
User asked about running site locally; I noticed that they would have no way to know that the whole site wouldn't build by default without this info here.
https://github.com/Kong/developer.konghq.com/tree/chore/readme-note?tab=readme-ov-file#developerkonghqcom
=> chore: Note about site generation in docs README

app/_how-tos/deck-get-started.md, app/_how-tos/docker-compose.md, app/_how-tos/gateway-install-helm-konnect.md, app/_how-tos/govern-mcp-traffic.md, app/_how-tos/install-gateway-read-only.md, app/_how-tos/observe-mcp-traffic.md, app/_how-tos/outbound-dns-resolver.md, app/_how-tos/plugin-dev-add-plugin-configuration.md, app/_how-tos/plugin-dev-add-plugin-testing.md, app/_how-tos/plugin-dev-deploy-plugins.md, app/_how-tos/private-hosted-zones.md, app/_how-tos/secure-mcp-traffic.md, tools/automated-tests/instructions-file.js, tools/automated-tests/instructions/extractor.js
Fixes url generation when generating instruction files and update extraction to use the new toggle switch
=> Fix automated tests instructions

app/gateway/debugger.md
Changed "data plane" to "Data plane" as it's the start of a bullet-point and so the first letter should be capitalized in this case. Very minor fix.
=> Fix: Grammatical improvement on bullet-point for Payload prerequisites

app/gateway/performance/benchmarks.md
Adding note about version support to the benchmark table. 
This came up on Slack: https://kongstrong.slack.com/archives/C03CTMSHP6C/p1756875453019479
The other proposed option is to remove unsupported versions from this table. Reviewers - what do you think?
=> update(gateway): Benchmark table note

app/_data/products/gateway.yml, app/_data/support/gateway.yml, app/gateway/third-party-support.md, docs/version-eol-or-sunset.md, jekyll-dev.yml
Fixes #2041
Gateway 3.8 moved into sunset support on Sept 11. Adjusting the doc to reflect this.
* Fixing the third-party support tables to only display supported versions
* Adding a short internal doc so that anyone can make this update
https://deploy-preview-2935--kongdeveloper.netlify.app/gateway/version-support-policy/#supported-versions
https://deploy-preview-2935--kongdeveloper.netlify.app/gateway/version-support-policy/#older-versions
https://deploy-preview-2935--kongdeveloper.netlify.app/gateway/third-party-support/
=> chore(gateway): EOL for Gateway 3.8

tools/broken-link-checker/config/ignored_targets.json
=> fix: add pages to broken links' ignored targets

app/_landing_pages/insomnia.yaml
The Manage Insomnia link was linking to the inso-cli page instead.
=> Correct link to Manage Insomnia

app/_data/glossary.yml, app/_how-tos/get-started-with-gateway.md
From
> 
> Definition of done
> The [Validate the Gateway Service and Route by proxying a reques](https://developer.konghq.com/gateway/get-started/#validate-the-gateway-service-and-route-by-proxying-a-request) section says that the curl command will return a 200 and it currently doesn't. It just returns a valid response. This is a change to the codeblog config not the text. To do this, add the flag display_headers: true to the existing block:
> {% validation request-check %}
> url: /mock/anything
> headers:
>   - 'apikey:top-secret-key'
> status_code: 200
> {% endvalidation %}
> Restructure the [Enable Authentication](https://developer.konghq.com/gateway/get-started/#enable-authentication) section per the Friction log
> Make the Caching section start with "Caching" and a link to the proxy …
=> Fix (Gateway): Friction Log Get Started

app/_how-tos/gateway-install-helm-konnect.md, app/_how-tos/gateway-install-helm-onprem.md
Fixes #2672 
Got the limitations from here: https://github.com/Kong/charts/blob/ea5eef28c5a601547061f048969fcb497ea17784/charts/kong/values.yaml#L657-L666
- /gateway/install/kubernetes/on-prem/#faqs
- /gateway/install/kubernetes/konnect/#faqs
=> fix(gateway): Add FAQ about installing via Helm without cluster permissions

app/deck/gateway/ping.md
The incorrectly documented command `deck file ping` has been corrected to the proper `deck gateway ping`.
=> fix(gateway): change command name in ping.md to `deck gateway ping`

.github/styles/base/Terms.yml, app/_how-tos/create-an-insomnia-plugin.md, app/_how-tos/konnect-reference-platform.md, app/_includes/tools/deck/install/osx.md, app/_includes/tools/inso-cli/install/osx.md, app/_includes/tools/insomnia/install/osx.md, app/_indices/deck.yaml, app/_landing_pages/deck.yaml, app/_landing_pages/inso-cli.yaml, app/_landing_pages/insomnia.yaml, app/konnect-reference-platform/orchestrator.md
To standardize the notation, I changed `MacOS` to `macOS`.
=> fix: change `MacOS` to `macOS` to standardize notation

app/gateway/performance/benchmarks.md
Update public benchmar perf tests for `3.12.0.0-rc.6`
The raw results could be found [here](https://docs.google.com/spreadsheets/d/1knu87tczpuTQ4a5si3WSkOoFHWf0pS8vqNpC44-Oxmw/edit?gid=565649791#gid=565649791)
Preview: https://deploy-preview-2964--kongdeveloper.netlify.app/gateway/performance/benchmarks/
=> 3 12 rc6 perf results

app/_kong_plugins/datakit/examples/authenticate-with-vault-secret.yaml, app/_kong_plugins/datakit/index.md
* Vault node: Curly braces don't get rendered unless we have `""` around them, so example was incorrect.
* Branch node: adding more info about inputs; removing `then/else` from outputs, as we don't want to mention these in docs. See https://kongstrong.slack.com/archives/C08QKTB0LFK/p1758875160835109?thread_ts=1758757233.438679&cid=C08QKTB0LFK for context.
https://deploy-preview-3055--kongdeveloper.netlify.app/plugins/datakit/#branch-node
https://deploy-preview-3055--kongdeveloper.netlify.app/plugins/datakit/examples/authenticate-with-vault-secret/
=> Fix(gateway): Datakit docs adjustments

app/_kong_plugins/ai-gcp-model-armor/examples/configure-gcp-model-armor.yaml
Adds missing variables to the GCP Model Armor sample.
https://deploy-preview-3070--kongdeveloper.netlify.app/plugins/ai-gcp-model-armor/examples/configure-gcp-model-armor/
=> fix(ai-gateway): add missing variables to GCP Model Armor example

app/konnect-platform/kong-identity.md
> Definition of done
> Uncomment and revise consumer group content on https://developer.konghq.com/kong-identity/
> The use case for this is it just allows users to apply plugins to clients as long as they map to consumer groups
> Information
> DRP: Smriti
> Aha: https://konghq.aha.io/epics/PLAT-E-33
> 
> Due date (optional)
> Sept, dependent on 3.12
> 
> Size
> small
Fixes #2597 
- https://deploy-preview-2831--kongdeveloper.netlify.app/kong-identity/
=> Feat (Konnect) Kong identity consumer group support
