Gemfile, Gemfile.lock
Note: this is a WIP, the plugin is outdated and requires some changes but should be good enough to start with and start generating content.
Adds support for `content_for`
=> Add contentblocks plugin

Gemfile, Gemfile.lock
Fixes https://www.ruby-lang.org/en/news/2024/05/16/dos-rexml-cve-2024-35176/
=> Bump rouge and rexml

app/_includes/landing_pages/card.md, app/_includes/landing_pages/concept_list.md, app/_includes/landing_pages/reference_list.md, app/_landing_pages/gateway.yaml
- created a product landing page for Gateway
- I also added icons to the cards design, formatting is weird, but they display
- Also added files for concept and reference lists so we can get those populated
- Do we need more/less content here? 
Preview link: https://deploy-preview-31--kongdeveloper.netlify.app/gateway/
=> Create Gateway product landing page

app/_includes/components/related_resources.html, app/_includes/landing_pages/header.md, app/_includes/landing_pages/structured_text.md, app/_includes/landing_pages/unordered_list.md, app/_kong_plugins/rate-limiting-advanced/index.md, app/_landing_pages/gateway/rate-limiting.yaml, app/_plugins/tags/related_resources.rb
https://deploy-preview-46--kongdeveloper.netlify.app/gateway/rate-limiting/
=> Gateway rate limiting landing page

app/_includes/components/faqs.html, app/_includes/landing_pages/command.md, app/_includes/landing_pages/entity_example.md, app/_includes/landing_pages/x_with_y.md, app/_landing_pages/deck.yaml, app/_landing_pages/deck_landing.yaml, app/_plugins/blocks/entity_example.rb, app/_tutorials/add-rate-limiting-tiers-with-kong-gateway.md
re: https://github.com/Kong/developer.konghq.com/pull/41
https://deploy-preview-44--kongdeveloper.netlify.app/deck_landing/
=> Deck landing page

app/_includes/landing_pages/tabs.md, app/_landing_pages/deck.yaml, app/_plugins/blocks/navtabs.rb, app/_plugins/tags/raise.rb
See OSX, Windows, Linux on https://deploy-preview-52--kongdeveloper.netlify.app/deck/
=> Add support for navtabs in landing pages

app/_landing_pages/demo.yaml
- Revised the existing RL landing page (demo)
- I wanted to add general info about what RL is, what it does, and then some info about which solution a user should choose
=> Rate Limiting landing page

app/_kong_plugins/rate-limiting/index.md, app/gateway/rate-limiting/strategies.md
=> Rate Limiting overview page 

app/_includes/landing_pages/text.md, app/_landing_pages/deck.yaml
Adjusting the decK landing page with more command examples + minor cleanup.
https://deploy-preview-57--kongdeveloper.netlify.app/deck/
=> decK commands for landing page

app/_landing_pages/deck.yaml
Added: 
- header for install section
- links to other sections
- Other tools section split beside the "what is decK section"
TODO: 
- Add more instructions to the What can decK do? section
- Add section for decK in Konnect
-
=> Update decK pge

app/_how-tos/add-rate-limiting-for-a-consumer-with-kong-gateway.md, app/_includes/components/entity_examples.html
* Break out tutorial steps into headings
* Adding more context for each step
* Clean up
https://deploy-preview-72--kongdeveloper.netlify.app/how-to/add-rate-limiting-for-a-consumer-with-kong-gateway/
=> Update consumer RL tutorial

app/_assets/javascripts/mode.js, app/_layouts/default.html
FOUC
Move fontawesome's script to the bottom.
=> Move dark mode system preference and manual selection to <head> to avoid

app/_how-tos/add-rate-limiting-tiers-with-kong-gateway.md, tailwind.config.js
Entities now appear in the info box: https://deploy-preview-83--kongdeveloper.netlify.app/how-to/add-rate-limiting-tiers-with-kong-gateway/
=> Fixing typos 

app/index.html
It's a quick and dirty solution to match the designs everywhere else. Add negative margin and padding to the links to match the card's padding.
=> Add background on hover to links in the homepage

app/_how-tos/add-rate-limiting-for-a-consumer-with-kong-gateway.md, app/_includes/cleanup/platform/konnect.md, app/_includes/how-tos/steps/apply_config.md
I applied Rick's feedback for the different steps (see my ACK on this slack thread: https://kongstrong.slack.com/archives/C06TLRHG8KX/p1727189057555369)
=> Apply Rick's feedback for RL consumer steps

app/_how-tos/add-rate-limiting-for-a-consumer-with-kong-gateway.md, app/_how-tos/add-rate-limiting-tiers-with-kong-gateway.md, app/_how-tos/add-rate-limiting-to-a-service-with-kong-gateway.md, app/_how-tos/enable-key-authentication-on-a-service-with-kong-gateway.md, app/_how-tos/multiple-rate-limits-window-sizes.md, app/_includes/components/faqs.html, app/_includes/how-tos/steps/apply_config.md, app/_includes/prereqs/entities.md, app/_landing_pages/gateway/rate-limiting.yaml
- split deck konnect commands for readability
- couple more edits to do
=> Chore: clean up from demo notes

app/_landing_pages/authentication.yaml
Applying feedback from https://kongstrong.slack.com/archives/C06TLRHG8KX/p1727192187909219.
=> Apply feedback to authentication page

app/_gateway_entities/consumer_group.md, app/_gateway_entities/plugin.md, app/_gateway_entities/service.md, app/_gateway_entities/target.md, app/_gateway_entities/workspace.md, app/_landing_pages/gateway/entities.yaml
Apply feedback from https://kongstrong.slack.com/archives/C06TLRHG8KX/p1727193707472369 and add missing descriptions.
=> Feedback for Kong Gateway entities page

app/_data/entity_examples/services/example-service.yml, app/_gateway_entities/service.md
[DOCU-4088](https://konghq.atlassian.net/browse/DOCU-4088)
[DOCU-4088]: https://konghq.atlassian.net/browse/DOCU-4088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Replace httpbin.org with httpbin.konghq.com

app/_how-tos/automate-tests.md, app/_includes/prereqs/create-collection.md, app/_includes/prereqs/tests.md, app/_includes/prereqs/tools/inso-cli.md, app/_landing_pages/insomnia/inso-cli.yaml
Formatting on the Inso CLI is a bit wonky.
=> Insomnia automate tests page

app/_landing_pages/insomnia/mock-servers.yaml
Will need to be updated with how-to/reference links
=> Insomnia: Mock servers landing page

package-lock.json, package.json
The issues with the package have been fixed so we can bump it again.
=> Bump spec-renderer

app/_landing_pages/insomnia/collections.yaml, app/insomnia/requests.md
=> Insomnia: Requests reference page

tools/track-docs-changes/config/sources.yml
Filling out sources.yaml
- [ N/A ] Every page is page one
- [ N/A ] Tested how-to docs. If not, note why here. 
- [ N/A ] All pages contain metadata
- [ N/A ] Any new docs link to existing docs.
=> Chore: Fill out source URLs file

app/_assets/entrypoints/api_spec.js, package-lock.json, package.json
=> Bump kongponents

app/_how-tos/get-started-with-gateway.md, app/_includes/how-tos/steps/ping-gateway.md, app/_includes/how-tos/tldr.html, app/_includes/prereqs/inline.md, app/_includes/prereqs/products/konnect.md, app/_includes/prereqs/tools/deck.md, app/_landing_pages/gateway.yaml, tools/track-docs-changes/config/sources.yml
Very draft, do not merge.
https://deploy-preview-174--kongdeveloper.netlify.app/how-to/get-started-with-gateway/
* ~liquid variables not getting parsed in tl;dr~
* ~How much detail do we want to go into here?~ much less than the original
* ~Should there be programmatic prereqs?~ - yes
* ~Should this page be testable in an automated way? My gut feel is no, but the Get Started guide specifically could be an outlier because it could test a clear basic flow~ - yes
*  ~need to convert everything to decK~ - done
* Is this page way too long? Do we want to have pages in a small nav like we will for plugin examples?
=> Kong Gateway: Getting started guide

app/_gateway_entities/upstream.md, app/_includes/components/entity_example/format/ui.md, app/_includes/entities/upstreams-targets-diagram.md
Pulled from here 
https://github.com/Kong/developer.konghq.com/pull/168
=> GW Entity upstreams

app/_how-tos/get-started-with-gateway.md, app/_includes/prereqs/products/konnect.md
Re-do the Konnect prereq and update the markdown accordingly.
=> Use KONNECT_PROXY_URL on the get started guide for konnect

app/_assets/stylesheets/index.css, app/_layouts/default.html
=> Add banner indicating that the site is in tech preview

app/_how-tos/add-rate-limiting-for-a-consumer-with-kong-gateway.md, app/_how-tos/add-rate-limiting-tiers-with-kong-gateway.md, app/_how-tos/add-rate-limiting-to-a-service-with-kong-gateway.md, app/_how-tos/create-a-custom-webhook-slack-with-kong-gateway.md, app/_how-tos/create-a-lambda-event-hook-with-kong-gateway.md, app/_how-tos/create-a-log-event-hook-with-kong-gateway.md, app/_how-tos/create-a-webhook-with-kong-gateway.md, app/_how-tos/custom-deck-object-defaults.md, app/_how-tos/enable-key-authentication-on-a-service-with-kong-gateway.md, app/_how-tos/multiple-rate-limits-window-sizes.md, app/_how-tos/restart-kong-gateway-container.md, app/_how-tos/set-up-ai-proxy-advanced-with-anthropic.md, app/_how-tos/set-up-ai-proxy-with-anthropic.md, app/_includes/cleanup/platform/konnect.md, app/_includes/how-tos/steps/ai-proxy-validate.md, app/_includes/prereqs/entities.md, app/_includes/prereqs/event-hook/restart-kong-gateway.md, app/_includes/prereqs/event-hook/slack.md, app/_includes/prereqs/products/konnect.md
- I only copyedited Gateway how tos, I omitted Insomnia ones since they are less likely to be reviewed this demo
=> Copyedit Gateway how tos and any how to includes

.github/workflows/check-links-scheduled.yml, package-lock.json, package.json
=> Fix netlify cli issue

app/_includes/components/entity_example/format/snippets/kic.md, app/_plugins/drops/entity_example/presenters/kic.rb
Fixed KIC example rendering when using nested configuration.
Feel free to edit and push to this PR before merging as needed
/plugins/ai-proxy/examples/anthropic-chat-route/
/gateway/entities/plugin/#set-up-a-plugin
=> Fix KIC entity example rendering

app/_how-tos/get-started-with-gateway.md
=> Getting started guide: Add -i flag to show more request info

app/_how-tos/get-started-with-gateway.md
=> Fix (gateway/gsg): Add missing api key to konnect validation

app/_gateway_entities/rbac.md, app/gateway/roles-and-permissions.md
Addresses https://github.com/Kong/developer.konghq.com/issues/208
=> Feat: Roles permissions

app/gateway/deployment-models.md
Migrated only the relevant content from here. 
https://deploy-preview-222--kongdeveloper.netlify.app/gateway/deployment-models/
https://konghq.atlassian.net/wiki/spaces/PM/pages/3036905549/Multi-tenancy+and+Kong+An+architectural+guide
=> Feat: Multi tenant

app/_data/entity_examples/config.yml, app/_gateway_entities/admin.md, app/_gateway_entities/group.md, app/_gateway_entities/key-set.md, app/_gateway_entities/key.md, app/_gateway_entities/keyring.md, app/_gateway_entities/license.md, app/_landing_pages/gateway/entities.yaml
Fixing entity card alignments and adding placeholders for all the entities this week.
Added some categorization, we can move things around later. This just gives us something to work with and not run into as many conflicts.
=> Entity cards

api-specs/konnect/mesh-control-planes/v0/openapi.yaml
Generated OAS files from platform-api.
=> feat(sdk): automated oas update

app/_data/entity_examples/config.yml, app/_gateway_entities/key-set.md, app/_gateway_entities/key.md, app/_how-tos/create-a-key-set-with-a-jwk.md, app/_how-tos/create-a-key-set-with-a-pem-key.md, app/_includes/components/entity_example/format/ui.md, tools/track-docs-changes/config/sources.yml
Fixes #217 
https://deploy-preview-260--kongdeveloper.netlify.app/gateway/entities/key/
https://deploy-preview-260--kongdeveloper.netlify.app/gateway/entities/key-set/
=> Feat: Key & Key Set entities

app/_data/entity_examples/config.yml, app/_gateway_entities/admin.md, app/_gateway_entities/rbac.md, app/_gateway_entities/workspace.md, app/_how-tos/configure-kong-manager-email.md, app/_includes/components/entity_example/format/ui.md, tools/track-docs-changes/config/sources.yml
https://deploy-preview-262--kongdeveloper.netlify.app/gateway/entities/admin/
fixes  https://github.com/Kong/developer.konghq.com/issues/215
Testing this is a real pain without the stub pages
=> Feat: Admin entity 

app/_layouts/default.html, app/_layouts/sitemap.xml, app/_plugins/generators/api_pages/index.rb, app/_plugins/generators/data/seo.rb, app/_plugins/generators/page_data.rb, app/_plugins/generators/sitemap.rb, app/_plugins/generators/sitemap/generator.rb, app/robots.txt, jekyll.yml
=> Add basic sitemap

app/_gateway_entities/ca-certificate.md, app/_gateway_entities/license.md, app/_gateway_entities/rbac.md, app/_gateway_entities/workspace.md
Follow up on QA for entities, particularly the workspaces "global" explanation.
=> QA for entities followup

app/_layouts/with_aside.html
=> chore: Disable h3s for content other than reference

app/gateway/deployment-models.md
=> Remove extra h1

app/_data/schemas/frontmatter/base.json, app/_includes/search_tags.html, app/_layouts/default.html, app/_plugins/generators/api_pages/page.rb, app/_plugins/generators/data/search_tags/api.rb, app/_plugins/generators/data/search_tags/base.rb, app/_plugins/generators/data/search_tags/concept.rb, app/_plugins/generators/data/search_tags/how_to.rb, app/_plugins/generators/data/search_tags/landing_page.rb, app/_plugins/generators/data/search_tags/plugin.rb, app/_plugins/generators/data/search_tags/plugin_example.rb, app/_plugins/generators/data/search_tags/reference.rb, app/_plugins/generators/page_data.rb, app/_plugins/generators/plugins/pages/example.rb, app/_plugins/generators/sitemap.rb, app/robots.txt, app/sitemap.xml, jekyll.yml
=> Add algolia meta tags

app/_how-tos/get-started-with-gateway.md
Fixes #245 
* Moved proxy caching and rate limiting to the end to avoid conflicts with other steps.
* rewrote the load balancing service update step to create a new service + route instead. The old option was causing problems with the workflow, and I didn't want users to suddenly have to open kong.yaml for the first time
To do: 
* validations for proxy caching and load balancing
=> Improvements to getting started guide 

app/_how-tos/configure-azure-key-vaults-as-a-vault-backend-with-vault-entity.md
=> Fix: Update Azure vault how-to prereqs

app/gateway/routing/expressions.md
Copies changes made in https://github.com/Kong/docs.konghq.com/pull/8348.
https://deploy-preview-354--kongdeveloper.netlify.app/gateway/routing/expressions/#allowed-type-and-operator-combinations
=> chore: Expressions router update

app/_assets/entrypoints/application.js, app/_assets/entrypoints/search.js, app/_assets/javascripts/apps/Search.vue, app/_assets/javascripts/apps/search/routing.js, app/_assets/javascripts/docsearch.js, app/_assets/stylesheets/index.css, app/_includes/badge.html, app/_includes/get_help.html, app/_includes/header.html, app/_layouts/default.html, app/search.html, package-lock.json, package.json, tailwind.config.js
=> WIP: Add search page and docsearch

app/_how-tos/add-rate-limiting-for-a-consumer-with-kong-gateway.md, app/_how-tos/add-rate-limiting-tiers-with-kong-gateway.md, app/_includes/prereqs/products/gateway.md
Fixes https://github.com/Kong/developer.konghq.com/actions/runs/13093776396/job/36533497041 from the weekend.
=> chore: Fix broken links

app/_how-tos/configure-fallback-route.md, tools/track-docs-changes/config/sources.yml
Fixes #330 
Q for reviewers:
*  do we think step 1 is necessary? I like it because it illustrates what's happening; without it, you can't tell that the fallback route did nothing before.
* I extrapolated the benefits of the redirect plugin from the config, but not sure if I missed anything.
https://deploy-preview-392--kongdeveloper.netlify.app/how-to/configure-fallback-route/
=> How-to: configuring a fallback route

app/_how-tos/enable-oidc-for-kong-manager.md, app/_how-tos/oidc-authenticated-group-mapping.md, app/_kong_plugins/openid-connect/changelog.md, app/_kong_plugins/openid-connect/index.md, app/_layouts/with_aside.html, tools/track-docs-changes/config/sources.yml
Fixes #414
The changelog is migrated 1 to 1 with links removed (there were only a couple). I don't think we need to do anything else there.
For the overview, I migrated:
* https://docs.konghq.com/hub/kong-inc/openid-connect/
* https://docs.konghq.com/hub/kong-inc/openid-connect/primary-config-params/
* https://docs.konghq.com/hub/kong-inc/openid-connect/support/
* the explanations and diagrams for all the flows in the how-to section, eg https://docs.konghq.com/hub/kong-inc/openid-connect/how-to/authentication/authorization-code-flow/.
The diagrams are currently not very pretty, they need a style fix - but that can come after merging at any time, it doesn't affect this PR.
https://deploy-preview-415--kongdeveloper.netlify.app/plugins/openid-connect/
=> Feat: OIDC overview and changelog

app/_how-tos/create-a-key-set-with-a-jwk.md
Fixes #250
https://deploy-preview-425--kongdeveloper.netlify.app/how-to/create-a-key-set-with-a-jwk/
=> Feat:  Create a Key Set with a JSON Web Key

.github/workflows/linting.yml
We no longer need to use my fork as all changes were accepted upstream
=> Switch to use official vale action

app/_landing_pages/gateway/network.yaml, app/gateway/network-ports-firewall.md, tools/track-docs-changes/config/sources.yml
Fixes #368 
https://deploy-preview-442--kongdeveloper.netlify.app/gateway/network-ports-firewall/
* I don't love the bullet points in the overview. Any suggestions for how to format that info differently?
https://github.com/Kong/developer.konghq.com/issues/443
=> Reference: Gateway network ports firewall

app/_kong_plugins/json-threat-protection/changelog.md, app/_kong_plugins/json-threat-protection/index.md, tools/track-docs-changes/config/sources.yml
=> JSON threat protection plugin (changelog and overview)

app/_gateway_entities/certificate.md, app/_gateway_entities/route.md, app/_gateway_entities/sni.md, tools/track-docs-changes/config/sources.yml
Information for a how-to doc for this does not exist, in an effort to migrate content this contains all of the information required for TLS routing, including updating the SNI docs, the Certificate docs, and the Routes entity docs. 
Fixes https://github.com/Kong/developer.konghq.com/issues/361
Fixes https://github.com/Kong/developer.konghq.com/issues/325
=> Proxy TLS information

app/_landing_pages/gateway/secrets-management.yaml
No issue applicable, it was faster to make changes than to open an issue.
https://deploy-preview-484--kongdeveloper.netlify.app/gateway/secrets-management/#secrets-management
=> fix: Secret rotation content on Secrets Management landing page

app/_landing_pages/gateway/secrets-management.yaml
Merged this too quickly 
https://github.com/Kong/developer.konghq.com/pull/484
Fixes #issue
=> Fix: Secrets management docs feedback

app/gateway/cp-dp-communication.md, tools/track-docs-changes/config/sources.yml
Fixes #456 
https://deploy-preview-486--kongdeveloper.netlify.app/gateway/cp-dp-communication/
https://github.com/Kong/developer.konghq.com/issues/511
- **HTTP/HTTPS Examples:** I tried them in env variable format and then kong.conf. I landed on kong.conf because "export KONG_" to me implies they can copy paste directly, but they shouldn't, they need to change some things. Thoughts?
=> Control plane/data plane forward proxy reference

app/_how-tos/configure-aws-secrets-manager-as-a-vault-backend-with-vault-entity.md, app/_how-tos/restart-kong-gateway-container.md, app/_how-tos/rotate-secrets-in-aws-secrets-manager.md, app/_how-tos/rotate-secrets-in-google-cloud-secret.md, app/_how-tos/rotate-secrets-in-hashicorp-vault.md, app/_includes/indices.html, app/_indices/gateway.yaml, app/_layouts/indices.html, app/_plugins/generators/indices.rb
Adds the index generator, plus a Gateway index page
https://deploy-preview-530--kongdeveloper.netlify.app/index/gateway/
=> Generate index pages

app/_data/entity_examples/gateway/routes/delete-route.yml, app/_data/entity_examples/gateway/routes/no-delete-route.yaml, app/_data/entity_examples/gateway/routes/other-example-route.yml, app/_how-tos/use-acl-with-consumer-groups.md, app/_kong_plugins/acl/index.md, tools/track-docs-changes/config/sources.yml
Fixes #495 
- https://deploy-preview-543--kongdeveloper.netlify.app/how-to/use-acl-with-consumer-groups/
=> Feat: How to use ACL with consumer groups

app/_includes/sections/dcg-regions.md, app/konnect/api-products/index.md, app/konnect/dedicated-cloud-gateways/index.md, app/konnect/dev-portal/app-reg.md, app/konnect/dev-portal/index.md, app/konnect/geos.md, tools/track-docs-changes/config/sources.yml
Fixes #318 
Source page: [Geographic Regions](https://docs.konghq.com/konnect/geo/)
Preview: https://deploy-preview-533--kongdeveloper.netlify.app/konnect/geos/
Stub pages:
- https://github.com/Kong/developer.konghq.com/issues/536
- https://github.com/Kong/developer.konghq.com/issues/534
- https://github.com/Kong/developer.konghq.com/issues/535
- DCG region tabs: Do you think these would be better off as subheadings instead of tabs for findabillity?
=> Konnect geos 

app/_includes/plugins/example.md, app/_kong_plugins/acme/examples/vault.yaml, app/_plugins/drops/plugin_config_example.rb
=> Basic rendering of env variables in plugin examples

app/gateway/performance/performance-benchmarks.md, app/gateway/performance/resource-sizing-guidelines.md, tools/track-docs-changes/config/sources.yml
Fixes #502 
https://deploy-preview-576--kongdeveloper.netlify.app/gateway/performance/performance-benchmarks/
=> Feat: Performance testing benchmarks

app/_assets/stylesheets/index.css
Slightly larger codephrase font size for better readability and alignment with the text around it.
Discussion/decision in https://kongstrong.slack.com/archives/C06TLRHG8KX/p1740582966091559.
=> chore: adjust code font size

app/_how-tos/get-started-with-ai-gateway.md, tools/track-docs-changes/config/sources.yml
Fixes #550 
https://deploy-preview-577--kongdeveloper.netlify.app/how-to/get-started-with-ai-gateway/
=> Feat: get started with AI Gateway 

app/_landing_pages/ai-gateway.yaml, app/ai-gateway/ai-audit-log-reference.md, tools/track-docs-changes/config/sources.yml
Fixes #556
https://deploy-preview-587--kongdeveloper.netlify.app/ai-gateway/ai-audit-log-reference/
=> Feat: AI audit logs reference page

app/stages-of-software-availability.md, tools/track-docs-changes/config/sources.yml
Fixes #559 
Since this document applies to all products I added all the products listed [here](https://github.com/Kong/developer.konghq.com/tree/main/app/_data/products), is that right? Or do we also need to add the Konnect apps? Or anything else?
https://deploy-preview-594--kongdeveloper.netlify.app/stages-of-software-availability/
=> Feat: Stages of software availability

app/_gateway_entities/admin.md, app/_gateway_entities/ca-certificate.md, app/_gateway_entities/certificate.md, app/_gateway_entities/consumer-group.md, app/_gateway_entities/consumer.md, app/_gateway_entities/event-hook.md, app/_gateway_entities/group.md, app/_gateway_entities/key-set.md, app/_gateway_entities/key.md, app/_gateway_entities/license.md, app/_gateway_entities/plugin.md, app/_gateway_entities/rbac.md, app/_gateway_entities/route.md, app/_gateway_entities/service.md, app/_gateway_entities/sni.md, app/_gateway_entities/target.md, app/_gateway_entities/upstream.md, app/_gateway_entities/vault.md, app/_gateway_entities/workspace.md, app/gateway/reserved-entity-names.md, tools/track-docs-changes/config/sources.yml
Fixes #558 
https://deploy-preview-613--kongdeveloper.netlify.app/gateway/reserved-entity-names/
=> Reserved entity names reference

app/_includes/layouts/main.html, app/_includes/toc.html, app/_layouts/with_aside.html
This is a proposal. How does the site look when the page title is in the TOC?
e.g. https://deploy-preview-595--kongdeveloper.netlify.app/gateway/networking/dns-config-reference/
=> Add page title to TOC

.github/styles/base/Dictionary.txt, app/_includes/service-catalog/service-catalog-discovery.html, app/_includes/service-catalog/service-catalog-integrations.html, app/_landing_pages/service-catalog.yaml, app/service-catalog/integrations/datadog.md, app/service-catalog/integrations/integrations.yaml, tools/track-docs-changes/config/sources.yml
This also contains all the includes and snippets to render the bottom part of the doc automatically. 
Fixes https://github.com/Kong/developer.konghq.com/issues/621
https://deploy-preview-622--kongdeveloper.netlify.app/service-catalog/integrations/datadog
=> Feat: Datadog integration + generated files

app/service-catalog/scorecards.md, tools/track-docs-changes/config/sources.yml
The service in this doc refers to a service catalog service not a gateway entity. 
Fixes https://github.com/Kong/developer.konghq.com/issues/641
https://deploy-preview-642--kongdeveloper.netlify.app/service-catalog/scorecards/
=> Service Catalog Score cards

app/gateway/cp-outage.md, tools/track-docs-changes/config/sources.yml
Fixes #551 and #552 
Source docs:
- https://docs.konghq.com/gateway/latest/kong-enterprise/cp-outage-handling-faq/
- https://docs.konghq.com/gateway/latest/kong-enterprise/cp-outage-handling/
https://deploy-preview-634--kongdeveloper.netlify.app/gateway/cp-outage/
=> Control plane outage reference

.github/workflows/linting.yml
=> Security fix: INC-456

app/gateway/quickstart-reference.md, tools/track-docs-changes/config/sources.yml
Fixes #784 
https://deploy-preview-820--kongdeveloper.netlify.app/gateway/quickstart-reference/
=> Feat: Quickstart script reference

app/gateway/db-less-mode.md, app/gateway/hybrid-mode.md, app/gateway/upgrade/backup-and-restore.md, app/gateway/upgrade/dual-cluster.md, app/gateway/upgrade/in-place.md, app/gateway/upgrade/rolling.md, tools/track-docs-changes/config/sources.yml
=> feat: Rolling upgrade

app/gateway/upgrade/blue-green.md, app/gateway/upgrade/dual-cluster.md, app/gateway/upgrade/in-place.md, tools/track-docs-changes/config/sources.yml
Fixes #653 
https://deploy-preview-831--kongdeveloper.netlify.app/gateway/upgrade/blue-green/
=> Feat: Blue-green upgrade

.github/styles/frontmatter/Dictionary.txt
I missed this in the last KIC platform PR as no content was using the new options.
=> Update Vale dictionary

app/_landing_pages/gateway-manager.yaml, app/gateway-manager/control-plane-groups.md, tools/track-docs-changes/config/sources.yml
Fixes https://github.com/Kong/developer.konghq.com/issues/883
https://deploy-preview-884--kongdeveloper.netlify.app/gateway-manager/control-plane-groups/
=> Feat: CP groups reference

app/serverless-gateways/index.md, tools/track-docs-changes/config/sources.yml
Fixed the table, added the info about securing with the request transformer plugin from the original doc. 
Fixes https://deploy-preview-902--kongdeveloper.netlify.app/serverless-gateways/
=> Fix: Secure backend traffic

app/_assets/entrypoints/hub.js, app/_data/plugin_support.yml, app/_data/plugins_support.yml, app/_includes/cards/plugin.html, app/plugins.html
Add `Support By` filter to plugins  query params and improve the way we handle array
=> Add `Support By` filter to plugins 

app/gateway/networking/dns-config-reference.md
Fixes #455 
- https://deploy-preview-925--kongdeveloper.netlify.app/gateway/networking/dns-config-reference/
=> Feat: DNS config reference

app/_includes/sections/azure-peering.md, app/assets/logos/konglogo-gradient-secondary.svg, app/dedicated-cloud-gateways/azure-peering.md, tools/track-docs-changes/config/sources.yml
Fixes https://github.com/Kong/developer.konghq.com/issues/900
https://deploy-preview-901--kongdeveloper.netlify.app/dedicated-cloud-gateways/azure-peering/
=> Feat: Azure vnet peering

app/_data/konnect_api_request.yml, app/_how-tos/kic-install.md, app/_includes/components/prereqs.html, app/_includes/how-tos/validations/request-check/snippet.md, app/_includes/konnect_api_request.html, app/_includes/prereqs/products/kic.md, app/_includes/prereqs/products/konnect-auth-only.md, app/_plugins/blocks/konnect_api_request.rb, app/_plugins/drops/konnect_api_request.rb, app/_plugins/filters/json_prettify.rb, tools/track-docs-changes/config/sources.yml
Fixes #708 
[/kubernetes-ingress-controller/install/](https://deploy-preview-846--kongdeveloper.netlify.app/kubernetes-ingress-controller/install/)
=> Install KIC page

app/_includes/upgrade/backup.md, app/_includes/upgrade/db-less.md, app/_includes/upgrade/flow.md, app/_includes/upgrade/hybrid.md, app/_includes/upgrade/traditional.md, app/gateway/upgrade/dual-cluster.md, app/gateway/upgrade/in-place.md, app/gateway/upgrade/index.md, app/gateway/upgrade/lts-upgrade.md, app/kic/version-support-policy.md, tools/track-docs-changes/config/sources.yml
Fixes #619 
https://deploy-preview-952--kongdeveloper.netlify.app/gateway/upgrade/
=> Gateway upgrade guide

app/_how-tos/authenticate-consumers-with-key-auth-enc.md, app/_kong_plugins/key-auth-enc/examples/enable-key-auth-encrypt.yaml, app/_kong_plugins/key-auth-enc/index.md
Fixes #926 
https://deploy-preview-961--kongdeveloper.netlify.app/how-to/authenticate-consumers-with-key-auth-enc/
=> How to: Key auth enc

app/gateway/incremental-config-sync.md, tools/track-docs-changes/config/sources.yml
Fixes #786 
https://deploy-preview-968--kongdeveloper.netlify.app/gateway/incremental-config-sync/
=> feat: Incremental config sync

.github/styles/base/Dictionary.txt, app/_landing_pages/dedicated-cloud-gateways.yaml, app/dedicated-cloud-gateways/aws-private-link.md, tools/track-docs-changes/config/sources.yml
Fixes https://github.com/Kong/developer.konghq.com/issues/972
https://deploy-preview-973--kongdeveloper.netlify.app/dedicated-cloud-gateways/aws-private-link/
=> Feat: AWS Private link

app/gateway/vulnerabilities.md
Based on convo in slack: https://kongstrong.slack.com/archives/C06TLRHG8KX/p1743706549757379
=> chore: update title of vulnerabilities doc

app/gateway-manager/control-plane-groups.md, tools/track-docs-changes/config/sources.yml
Fixes #1003 
https://deploy-preview-1057--kongdeveloper.netlify.app/gateway-manager/control-plane-groups/
=> Feat: control plane groups migrate config info

app/_assets/entrypoints/application.js, app/_assets/javascripts/apps/SearchModal.vue, app/_data/products/ai-gateway.yml, app/_data/schemas/frontmatter/base.json, app/_how-tos/get-started-with-ai-gateway.md, app/_includes/components/prereqs.html, app/_landing_pages/ai-gateway.yaml, app/_landing_pages/ai-gateway/ai-providers.yaml, app/_landing_pages/deck.yaml, app/_plugins/blocks/validation.rb, app/_plugins/drops/prereqs.rb, app/ai-gateway/ai-audit-log-reference.md, app/ai-gateway/monitor-ai-llm-metrics.md
Add ai-gateway as a product and udpate a few pages to use `ai-gateway` instead of `gateway`
Fixes #910
=> Add ai-gateway as a product and udpate a few pages

app/_indices/analytics.yaml, app/_indices/deck.yaml, app/_indices/gateway.yaml, app/_indices/insomnia.yaml, app/_indices/konnect-platform.yaml, app/_indices/kubernetes-ingress-controller.yaml, app/_indices/mesh.yaml, app/_indices/portal.yaml, app/_indices/service-catalog.yaml, app/index.html
Add an `All Documentation` link to all tiles on the homepage + bootstrap associated indices
=> Bootstrap all index pages + add to homepage

app/_how-tos/deploy-mesh-on-kubernetes.md, app/_includes/cleanup/products/mesh.md, app/_includes/prereqs/helm.md, app/_landing_pages/mesh/overview.yaml, tools/track-docs-changes/config/sources.yml
=> Feat: Install mesh

app/mesh/cert-manager.md, app/mesh/secrets.md, tools/track-docs-changes/config/sources.yml
Fixes #1092 
https://deploy-preview-1093--kongdeveloper.netlify.app/mesh/cert-manager/
=> Feat: Mesh Cert Manager

app/mesh/license.md, tools/track-docs-changes/config/sources.yml
Fixes #1105 
https://deploy-preview-1106--kongdeveloper.netlify.app/mesh/license/
=> Mesh: License

app/_landing_pages/konnect-platform.yaml, app/konnect-platform/self-managed-migration.md, jekyll.yml, tools/track-docs-changes/config/sources.yml
Fixes #1055 
https://deploy-preview-1104--kongdeveloper.netlify.app/konnect-platform/self-managed-migration/
=> Migrate self-managed to Konnect

app/_gateway_entities/workspace.md
Clarification for workspace route/service collision precedence. Based on Slack thread: https://kongstrong.slack.com/archives/C03CTMSHP6C/p1744188119373439
=> Workspace clarification

app/_how-tos/sign-gateway-audit-logs.md, app/_how-tos/validate-gateway-audit-log-signatures.md, tools/track-docs-changes/config/sources.yml
Fixes #604
- https://deploy-preview-1119--kongdeveloper.netlify.app/how-to/sign-gateway-audit-logs/
- https://deploy-preview-1119--kongdeveloper.netlify.app/how-to/validate-gateway-audit-log-signatures/
The validation how-to failed for me so this will need to be reviewed.
=> Feat: How to sign audit logs

app/_assets/stylesheets/index.css, app/_kong_plugins/openid-connect/examples/cert-bound-access-tokens.yaml, app/_kong_plugins/openid-connect/index.md, tools/track-docs-changes/config/sources.yml
Fixes #1158 
Fixes #1156 (not a how-to at all)
Some notes:
- Turned all of the various h3s into h4s so that the sidebar isn't impossible to use.
- The table of FAPI standards has some examples, but we don't have examples for everything. I think that's okay - if someone runs into that and has to develop one, that's when we can add them.
- had to adjust h4 spacing a bit so it's not squished
- For debugging, removed methods that don't actually exist anymore (eg session_compression is deprecated)
https://deploy-preview-1184--kongdeveloper.netlify.app/plugins/openid-connect/#financial-grade-api-fapi
https://deploy-preview-1184--kongdeveloper.netlify.app/plugins/openid-connect/#debugging-the-oidc-plugin
=> OIDC references

app/_data/series.yml, app/_how-tos/plugin-dev-add-plugin-configuration.md, app/_how-tos/plugin-dev-add-plugin-testing.md, app/_how-tos/plugin-dev-consume-external-services.md, app/_how-tos/plugin-dev-deploy-plugins.md, app/_how-tos/plugin-dev-set-up-plugin-project.md, app/_landing_pages/custom-plugins.yaml, app/custom-plugins/custom-logic.md, app/custom-plugins/deployment-options.md, tools/track-docs-changes/config/sources.yml
Fixes #1058
Fixes #1059
Fixes #1060
Fixes #1061
Fixes #1062
- https://deploy-preview-1181--kongdeveloper.netlify.app/custom-plugins/#get-started
- https://deploy-preview-1181--kongdeveloper.netlify.app/custom-plugins/get-started/set-up-plugin-project/
- https://deploy-preview-1181--kongdeveloper.netlify.app/custom-plugins/get-started/add-plugin-testing/
- https://deploy-preview-1181--kongdeveloper.netlify.app/custom-plugins/get-started/add-plugin-configuration/
- https://deploy-preview-1181--kongdeveloper.netlify.app/custom-plugins/get-started/consume-external-services/
- https://deploy-preview-1181--kongdeveloper.netlify.app/custom-plugins/get-started/deploy-plugins/
=> Feat: Get started with custom plugins

app/_how-tos/configure-oidc-with-session-auth.md, app/_includes/how-tos/validations/request-check/index.html, app/_includes/how-tos/validations/request-check/snippet.md, app/_kong_plugins/openid-connect/examples/session-auth.yaml, tools/track-docs-changes/config/sources.yml
Fixes #1143 
Also adding `--cookie-jar` and `--cookie` attributes for the curl request check.
Not including logout functionality in this (separate source page), as I couldn't get it to work reliably.
http://deploy-preview-1194--kongdeveloper.netlify.app/how-to/configure-oidc-with-session-auth/
=> OIDC: Session auth

app/_how-tos/configure-oidc-with-password-grant.md, app/_how-tos/configure-oidc-with-refresh-token.md, app/_kong_plugins/openid-connect/examples/refresh-token.yaml, tools/track-docs-changes/config/sources.yml
=> OIDC: refresh token how-to

app/konnect-compatibility.md
Fixes https://kongstrong.slack.com/archives/CDSTDSG9J/p1744771182817609
https://deploy-preview-1195--kongdeveloper.netlify.app/konnect-compatibility/
=> Konnect 3.10 compatibility

app/_how-tos/configure-oidc-with-acl-auth.md, app/_how-tos/configure-oidc-with-consumers.md, app/_how-tos/configure-oidc-with-introspection.md, app/_how-tos/configure-oidc-with-password-grant.md, app/_how-tos/configure-oidc-with-refresh-token.md, app/_how-tos/configure-oidc-with-session-auth.md, app/_how-tos/configure-oidc-with-user-info-auth.md, app/_includes/prereqs/auth/oidc/keycloak-password.md, app/_kong_plugins/openid-connect/examples/consumer-auth.yaml, tools/track-docs-changes/config/sources.yml
Fixes #1147 
https://deploy-preview-1204--kongdeveloper.netlify.app/plugins/openid-connect/examples/consumer-auth/
https://deploy-preview-1204--kongdeveloper.netlify.app/how-to/configure-oidc-with-consumers/
=> OIDC consumers

app/konnect-compatibility.md, tools/track-docs-changes/config/sources.yml
Fixes #1171 
https://deploy-preview-1207--kongdeveloper.netlify.app/konnect-compatibility/#faqs
=> Konnect upgrade FAQ

tools/track-docs-changes/config/sources.yml
=> Remove dupes from sources.yaml [skip ci]

app/konnect-platform/konnect-sso.md, app/konnect-platform/teams-and-roles.md, tools/track-docs-changes/config/sources.yml
Fixes #1172 
*Notes for reviewers:* 
- The existing OIDC doc contained info about scopes, claims, and team mappings that were already in the APIs or in the SSO dev site doc, so I omitted them.
=> Konnect identity management

app/_how-tos/configure-oidc-with-acl-auth.md, app/_how-tos/configure-oidc-with-client-credentials.md, app/_how-tos/configure-oidc-with-consumers.md, app/_how-tos/configure-oidc-with-introspection.md, app/_how-tos/configure-oidc-with-kong-oauth2.md, app/_how-tos/configure-oidc-with-password-grant.md, app/_how-tos/configure-oidc-with-refresh-token.md, app/_how-tos/configure-oidc-with-session-auth.md, app/_how-tos/configure-oidc-with-user-info-auth.md, app/_kong_plugins/openid-connect/examples/client-credentials.yaml, app/_kong_plugins/openid-connect/examples/introspection-auth.yaml, app/_kong_plugins/openid-connect/examples/kong-oauth-token.yaml, app/_kong_plugins/openid-connect/examples/password.yaml, app/_kong_plugins/openid-connect/examples/refresh-token.yaml, app/_kong_plugins/openid-connect/examples/session-auth.yaml, app/_kong_plugins/openid-connect/examples/user-info-auth.yaml, tools/track-docs-changes/config/sources.yml
Fixes #1153 
https://deploy-preview-1218--kongdeveloper.netlify.app/plugins/openid-connect/examples/kong-oauth-token/
https://deploy-preview-1218--kongdeveloper.netlify.app/how-to/configure-oidc-with-kong-oauth2/
=> OIDC with kong oauth token

.github/workflows/check-for-changes-in-docs-repo.yml, tools/track-docs-changes/config/sources.yml, tools/track-docs-changes/index.js
=> Remove more dupes

app/_how-tos/configure-oidc-with-introspection.md, app/_how-tos/configure-oidc-with-jwt-auth.md, app/_how-tos/configure-oidc-with-kong-oauth2.md, app/_how-tos/configure-oidc-with-refresh-token.md, app/_includes/plugins/oidc/client-auth.md, app/_kong_plugins/openid-connect/examples/jwt-access-token.yaml, tools/track-docs-changes/config/sources.yml
=> OIDC with JWT auth

app/_how-tos/configure-oidc-with-claims-based-auth.md, app/_kong_plugins/openid-connect/examples/claims-based-auth.yaml, app/_kong_plugins/openid-connect/index.md, tools/track-docs-changes/config/sources.yml
Fixes #1149 
https://deploy-preview-1227--kongdeveloper.netlify.app/plugins/openid-connect/#claims-based-authorization
https://deploy-preview-1227--kongdeveloper.netlify.app/plugins/openid-connect/examples/claims-based-auth/
https://deploy-preview-1227--kongdeveloper.netlify.app/how-to/configure-oidc-with-consumers/
=> OIDC claims-based auth

app/_includes/components/entity_example/format/snippets/kic.md, app/_includes/how-tos/validations/rate-limit-check/snippet.md, app/_includes/how-tos/validations/request-check/index.html, app/_includes/how-tos/validations/request-check/snippet.md, app/_includes/http_request.html, app/_includes/k8s/httproute.md, app/_includes/prereqs/entities/kic.md, app/_includes/prereqs/products/kic.md, app/_plugins/blocks/entity_example.rb, app/_plugins/blocks/http_request.rb, app/_plugins/drops/entity_example/presenters/kic.rb, app/_plugins/drops/http_request.rb
Adds a new `http_request` block and fixes some KIC prerequisites
=> KIC tooling updates

app/_references/gateway/pdk/reference/3.10/kong.websocket.client.md, app/_references/gateway/pdk/reference/3.10/kong.websocket.upstream.md, app/_references/gateway/pdk/reference/3.4/kong.websocket.client.md, app/_references/gateway/pdk/reference/3.4/kong.websocket.upstream.md, app/_references/gateway/pdk/reference/3.7/kong.websocket.client.md, app/_references/gateway/pdk/reference/3.7/kong.websocket.upstream.md, app/_references/gateway/pdk/reference/3.8/kong.websocket.client.md, app/_references/gateway/pdk/reference/3.8/kong.websocket.upstream.md, app/_references/gateway/pdk/reference/3.9/kong.websocket.client.md, app/_references/gateway/pdk/reference/3.9/kong.websocket.upstream.md, app/gateway/traffic-control/proxying.md, tools/track-docs-changes/config/sources.yml
Fixes #331 
Fixes #1015 
- https://deploy-preview-1230--kongdeveloper.netlify.app/gateway/traffic-control/proxying/
- https://deploy-preview-1230--kongdeveloper.netlify.app/gateway/pdk/reference/kong.websocket.client/
- https://deploy-preview-1230--kongdeveloper.netlify.app/gateway/pdk/reference/kong.websocket.upstream/
=> Feat: Routing and proxying

app/_data/products/kic.yml, app/_indices/kubernetes-ingress-controller.yaml, app/_plugins/generators/site_data.rb, app/kubernetes-ingress-controller/faq/upgrading-gateway.md, app/kubernetes-ingress-controller/faq/upgrading-ingress-controller.md, tools/track-docs-changes/config/sources.yml
Resolves #726 
Resolves #727 
[/kubernetes-ingress-controller/faq/upgrading-gateway/](https://deploy-preview-1241--kongdeveloper.netlify.app/kubernetes-ingress-controller/faq/upgrading-gateway/)
[/kubernetes-ingress-controller/faq/upgrading-ingress-controller/](https://deploy-preview-1241--kongdeveloper.netlify.app/kubernetes-ingress-controller/faq/upgrading-ingress-controller/)
=> KIC Upgrading

app/index.html
=> Fix: remove use case

.github/styles/frontmatter/Keys.txt, app/_data/entity_examples/kic/services/httpbin-service.yaml, app/_how-tos/kic-customize-load-balancing.md, app/_how-tos/kic-proxy-rewriting-paths.md, app/_includes/k8s/httproute.md, app/_includes/prereqs/products/kic.md, app/_indices/kubernetes-ingress-controller.yaml, app/_kong_plugins/request-transformer/examples/rewrite-path.yaml, app/kubernetes-ingress-controller/reference/host-manipulation.md, app/kubernetes-ingress-controller/reference/path-manipulation.md, app/manifests/kic/httpbin-service.yaml, tools/track-docs-changes/config/sources.yml
Resolves #738
Resolves #739
Resolves #740
[/kubernetes-ingress-controller/routing/rewriting-paths/](https://deploy-preview-1257--kongdeveloper.netlify.app/kubernetes-ingress-controller/routing/rewriting-paths/)
[/kubernetes-ingress-controller/load-balancing/](https://deploy-preview-1257--kongdeveloper.netlify.app/kubernetes-ingress-controller/load-balancing/)
[/kubernetes-ingress-controller/reference/host-manipulation/](https://deploy-preview-1257--kongdeveloper.netlify.app/kubernetes-ingress-controller/reference/host-manipulation/)
[/kubernetes-ingress-controller/reference/path-manipulation/](https://deploy-preview-1257--kongdeveloper.netlify.app/kubernetes-ingress-controller/reference/path-manipulation/)
=> Add KIC request manipulation section

.github/styles/base/Dictionary.txt, app/_how-tos/visualize-ai-gateway-metrics-with-kibana.md, tools/track-docs-changes/config/sources.yml
Fixes #808
- https://deploy-preview-1263--kongdeveloper.netlify.app/how-to/visualize-ai-gateway-metrics-with-kibana/
=> Feat: AI Gateway observability how-to

app/_kong_plugins/openid-connect/examples/headers.yaml, app/_kong_plugins/openid-connect/examples/logout.yaml, tools/track-docs-changes/config/sources.yml
=> OIDC headers and logout examples

app/_data/entity_examples/kic/routes/httpbin.yaml, app/_how-tos/kic-fallback-config-backfill.md, app/_how-tos/kic-fallback-config-exclude.md, app/_how-tos/kic-service-healthchecks.md, app/_includes/how-tos/validations/request-check/index.html, app/_includes/how-tos/validations/request-check/snippet.md, app/_includes/k8s/content/fallback-configuration/scenario-setup.md, app/kubernetes-ingress-controller/fallback-configuration.md, app/kubernetes-ingress-controller/kic-high-availability.md, app/kubernetes-ingress-controller/last-known-good-config.md, tools/track-docs-changes/config/sources.yml
Resolves #742
Resolves #743
Resolves #744 
[/kubernetes-ingress-controller/service-health-checks/](https://deploy-preview-1274--kongdeveloper.netlify.app/kubernetes-ingress-controller/service-health-checks/)
[/kubernetes-ingress-controller/last-known-good-config/](https://deploy-preview-1274--kongdeveloper.netlify.app/kubernetes-ingress-controller/last-known-good-config/)
[/kubernetes-ingress-controller/fallback-configuration/](https://deploy-preview-1274--kongdeveloper.netlify.app/kubernetes-ingress-controller/fallback-configuration/)
[/kubernetes-ingress-controller/fallback-configuration/backfill/](https://deploy-preview-1274--kongdeveloper.netlify.app/kubernetes-ingress-controller/fallback-configuration/backfill/)
[/kubernetes-ingress-controller/fallback-configuration/exclude/](https:// …
=> KIC high availability

app/_how-tos/kic-fallback-config-backfill.md, app/_includes/cleanup/inline.md, app/_includes/how-tos/validations/vault-secret/index.html, app/_includes/how-tos/validations/vault-secret/snippet.md, app/_includes/indices.html, app/_includes/prereqs/products/kic.md, app/_plugins/drops/entity_example/presenters/kic.rb, app/_plugins/generators/data/breadcrumbs.rb, app/_plugins/generators/indices.rb, tools/track-docs-changes/config/sources.yml
Platform updates, mostly related to KIC rendering
=> Fix KIC prereq rendering

app/_how-tos/kic-verify-upstream-tls.md, app/_includes/k8s/verify-upstream-tls-ca.md, app/_indices/kubernetes-ingress-controller.yaml, tools/track-docs-changes/config/sources.yml
Fixes #749
[/kubernetes-ingress-controller/verify-upstream-tls/](https://deploy-preview-1291--kongdeveloper.netlify.app/kubernetes-ingress-controller/verify-upstream-tls/)
=> Add TLS verification guide

app/_how-tos/kic-proxy-https.md, app/_how-tos/kic-proxy-tcp-sni.md, app/_includes/how-tos/validations/request-check/index.html, app/_includes/how-tos/validations/request-check/snippet.md, app/_includes/k8s/configure-tcp-listen.md, app/_includes/k8s/httproute.md, app/_indices/kubernetes-ingress-controller.yaml, app/manifests/kic/echo-service.yaml, exe/build, tools/track-docs-changes/config/sources.yml
Resolves #732 
[/kubernetes-ingress-controller/routing/https-tls-termination/](https://deploy-preview-1318--kongdeveloper.netlify.app/kubernetes-ingress-controller/routing/https-tls-termination/)
[/kubernetes-ingress-controller/routing/tcp-by-sni/](https://deploy-preview-1318--kongdeveloper.netlify.app/kubernetes-ingress-controller/routing/tcp-by-sni/)
=> KIC Proxy HTTPS / TLS

app/_includes/indices.html, app/_includes/toc.html, app/_indices/operator.yaml, app/_layouts/indices.html, app/_layouts/install.html, app/_layouts/with_aside.html, app/_plugins/generators/indices.rb, app/_plugins/hooks/post_process_html.rb
Add TOC to index pages. Add the ability to have groups of sections (needed for Operator)
=> Index page updates

app/_landing_pages/gateway.yaml, app/gateway/changelog.md
https://deploy-preview-1414--kongdeveloper.netlify.app/gateway/changelog/
Fixes #947
=> Changelog for gateway

api-specs/gateway/admin-ee/3.10/openapi.yaml, api-specs/gateway/admin-oss/3.9/openapi.yaml, api-specs/plugins/acme/openapi.yaml, api-specs/plugins/ai-rag-injector/openapi.yaml, api-specs/plugins/ai-semantic-cache/openapi.yaml, api-specs/plugins/graphql-proxy-cache-advanced/openapi.yaml, api-specs/plugins/jwt/openapi.yaml, api-specs/plugins/key-auth/openapi.yaml, api-specs/plugins/mtls-auth/openapi.yaml, api-specs/plugins/openid-connect/openapi.yaml, api-specs/plugins/proxy-cache-advanced/openapi.yaml, api-specs/plugins/proxy-cache/openapi.yaml, api-specs/plugins/vault-auth/openapi.yaml
=> Replace API spec URL

api-specs/gateway/admin-oss/3.9/openapi.yaml
Generated OAS files from docs.konghq.com
=> feat(sdk): automated oas update - from docs repo

app/_how-tos/terraform-gateway-authentication.md, app/_includes/card.html, app/_includes/landing_pages/header.md, app/_includes/prereqs/terraform.md, app/_includes/uses.html, app/_landing_pages/terraform.yaml, tools/track-docs-changes/config/sources.yml
[/terraform/](https://deploy-preview-1379--kongdeveloper.netlify.app/terraform/)
=> Update Terraform landing page

app/_how-tos/knep/get-started-with-event-gateway.md, app/_landing_pages/event-gateway.yaml
Removing placeholder text, adding missing metadata, and doing a minor copyedit.
https://deploy-preview-1452--kongdeveloper.netlify.app/knep/get-started/
=> Clean up knep get started guide

app/_how-tos/configure-datastore.md, app/_includes/install/gateway/linux.html, app/_includes/prereqs/postgres.md, tools/track-docs-changes/config/sources.yml
=> Install datastore

app/_layouts/default.html, app/robots.txt, jekyll.yml
FInal tweaks before release:
* Uncomment meta robots tags
* Enable OneTrust cookies in prod
* Allow all pages in robots.txt in prod, disallow them in the rest of the envs
* Remove `tech preview` banner
=> Pre-release changes

app/dev-portal/snippets.md
=> docs(portals): snippets typo

app/gateway-manager/data-plane-reference.md
Carrying over from docs site
https://github.com/Kong/docs.konghq.com/pull/8775
=> Update parameter-reference.md for vitals

app/_assets/entrypoints/application.js, app/_layouts/default.html, package-lock.json, package.json
=> Use ddog rum instead of vwo

.github/styles/frontmatter/Keys.txt, app/_kong_plugins/ai-proxy/examples/sdk-azure-deployment.yaml, app/_kong_plugins/ai-proxy/examples/sdk-dynamic-model-selection.yml, app/_kong_plugins/ai-proxy/examples/sdk-multiple-providers.yaml, app/_kong_plugins/ai-proxy/examples/sdk-unsupported-model.yaml, app/_kong_plugins/ai-proxy/index.md, app/_layouts/plugins/example.html, app/_plugins/drops/plugin_config_example.rb, app/_plugins/generators/plugins/pages/example.rb, app/_plugins/generators/plugins/plugin.rb
Fixes https://github.com/Kong/developer.konghq.com/issues/1549
=> Group plugin examples

app/advanced-analytics/explorer.md
The non-dev-portal cherry pick from this PR
https://github.com/Kong/docs.konghq.com/pull/8785
Fixes #issue
=> Fix: Add new data to Explorer FAQ

app/_assets/stylesheets/index.css
Fixes an issue on mobile where the buttons get cut off and can't scroll to them
Fixes https://github.com/Kong/developer.konghq.com/issues/1527
=> Set nav height to h-dvh

app/_how-tos/outbound-dns-resolver.md, app/_how-tos/private-hosted-zones.md, app/_includes/prereqs/aws-cli.md, app/dedicated-cloud-gateways/reference.md, app/serverless-gateways/index.md
Fixes https://github.com/Kong/developer.konghq.com/issues/1449
https://deploy-preview-1495--kongdeveloper.netlify.app/dedicated-cloud-gateways/private-hosted-zones/
https://deploy-preview-1495--kongdeveloper.netlify.app/dedicated-cloud-gateways/outbound-dns-resolver/
Needed the preview links for SME review.
=> Feat: Private DNS documentation

app/_plugins/drops/entity_example/presenters/deck.rb
Fixes https://github.com/Kong/developer.konghq.com/issues/1556
=> Render partials in deck entity_examples

app/ai-gateway/load-balancing.md
Fixes description of the latency algorithm for AI Proxy advanced.
=> fix: Update latency algorithm description

app/_gateway_entities/consumer.md, app/_how-tos/terraform-gateway-authentication.md, app/_landing_pages/konnect-api.yaml, app/dev-portal/apis.md, app/dev-portal/publishing.md
Fixes:
- Clarify that key auth has to be configured a specific way for central consumers (https://kongstrong.slack.com/archives/CA42V003B/p1747747053933969)
- Make API builder spec links more obviously related to Dev Portal (https://kongstrong.slack.com/archives/CAW1MAFLZ/p1747394683353619)
- Fix h1 in Terraform how to
=> Fix: misc QA fixes

app/_gateway_entities/vault.md
=> Provide some details on the Konnect Config Store #8813

.github/styles/base/Dictionary.txt, app/_data/products/operator.yml, app/_how-tos/operator-get-started-hybrid-install.md, app/_how-tos/operator-get-started-kic-install.md, app/_includes/k8s/httproute.md, app/_includes/prereqs/kubernetes/gateway-api.md, app/operator/changelog.md
Migrating the following:
- https://github.com/Kong/docs.konghq.com/pull/8791
- https://github.com/Kong/docs.konghq.com/pull/8814
For reviewers:
- I think I updated the correct files for the KGO version update, but I'm not sure. 
- https://deploy-preview-1639--kongdeveloper.netlify.app/operator/changelog/
- https://deploy-preview-1639--kongdeveloper.netlify.app/operator/support-policy/
- https://deploy-preview-1639--kongdeveloper.netlify.app/operator/dataplanes/get-started/hybrid/install/#install-crds (see the updated Gateway API version)
=> KGO 1.6.1 changes

app/_how-tos/add-rate-limiting-for-a-consumer-with-kong-gateway.md
=> Remove instruction

.github/styles/base/Dictionary.txt, app/_indices/gateway.yaml, app/gateway/network/dns-config-reference.md, app/gateway/performance/benchmarks.md, app/gateway/performance/establish-a-benchmark.md, app/gateway/performance/optimize.md, tools/track-docs-changes/config/sources.yml
Fixes #1630 
Fixes #501 
Fixes #503 
Fixes #500 (not doing this one, I don't think this needs a landing page)
=> Performance docs

app/_includes/prereqs/entities/gateway.md
=> Fix: change to "preconfigured entities" to "required entities"

app/_kong_plugins/aws-lambda/examples/dedicated-cloud-gateway.yaml, app/_kong_plugins/http-log/index.md, app/_kong_plugins/request-transformer-advanced/index.md, app/gateway/cp-outage.md, app/gateway/traffic-control/proxying.md
Fixes #1519 
- https://deploy-preview-1669--kongdeveloper.netlify.app/plugins/aws-lambda/examples/dedicated-cloud-gateway/
- https://deploy-preview-1669--kongdeveloper.netlify.app/plugins/http-log/#can-the-http-log-plugin-expose-latency-metrics-for-individual-phases-of-the-request-lifecycle-such-as-rewrite-access-header-filter-and-body-filter (just FAQ)
- https://deploy-preview-1669--kongdeveloper.netlify.app/plugins/request-transformer-advanced/#can-i-use-the-request-transformer-advanced-plugin-to-rename-or-replace-xml-in-the-request-body (just FAQ)
- https://deploy-preview-1669--kongdeveloper.netlify.app/gateway/cp-outage/#faqs (all FAQs)
- Proxying page was just adding a search alias to help users find the page
=> Misc improvements from customer issues

app/_includes/k8s/httproute.md, app/_includes/prereqs/kubernetes/gateway-api.md
https://deploy-preview-1685--kongdeveloper.netlify.app/operator/dataplanes/get-started/hybrid/install/#install-crds
=> Fix KIC guides

app/_indices/gateway.yaml, app/gateway-manager/data-plane-reference.md, app/gateway/cp-dp-communication.md, tools/track-docs-changes/config/sources.yml
Migrate https://docs.konghq.com/konnect/gateway-manager/troubleshoot/
Fixes #1636 
https://deploy-preview-1687--kongdeveloper.netlify.app/gateway-manager/data-plane-reference/#troubleshoot-data-plane-nodes
=> Troubleshooting data plane nodes

app/_how-tos/collect-metrics-with-prometheus.md, app/_how-tos/kic-observability-prometheus-grafana.md, app/_indices/gateway.yaml, app/_landing_pages/gateway/monitoring.yaml, app/_landing_pages/gateway/secrets-management.yaml, tools/track-docs-changes/config/sources.yml
Fixes #1505 
**Note for reviewers:** I plan to add links to the other monitoring how tos and the tracing reference in those PRs if this is published before those.
https://deploy-preview-1732--kongdeveloper.netlify.app/gateway/monitoring/
=> Monitoring landing page

app/gateway/postgresql-reference.md, tools/track-docs-changes/config/sources.yml
Fixes #1632 
Redirect PR: https://github.com/Kong/docs.konghq.com/pull/8838
https://deploy-preview-1746--kongdeveloper.netlify.app/gateway/postgresql-tls-reference/
=> Migration: postgres tls reference

app/_gateway_entities/rbac.md, app/gateway/kong-manager/configuration.md, tools/track-docs-changes/config/sources.yml
Fixes #1629 
- https://deploy-preview-1747--kongdeveloper.netlify.app/gateway/kong-manager/configuration/#kong-manager-networking
- https://deploy-preview-1747--kongdeveloper.netlify.app/gateway/entities/rbac/#kong-manager-authentication
=> Kong Manager networking

app/_includes/install/gateway/linux.html, app/_indices/gateway.yaml, app/gateway/fips-support.md, app/gateway/version-support-policy.md, tools/track-docs-changes/config/sources.yml
Fixes #1611 
**Question for reviewers**: 
- I think I got the package conditional versions correct from the [original doc](https://docs.konghq.com/gateway/latest/kong-enterprise/fips-support/) in the opening paragraph, but I think something happened to the original doc. 
- ChatGPT helped me with the note formatting in the linux.html page, so just make sure everything looks correct there.
Pages:
- https://deploy-preview-1748--kongdeveloper.netlify.app/gateway/fips-support/
- https://deploy-preview-1748--kongdeveloper.netlify.app/gateway/install/ (added a note to the Ubuntu and RedHat install tabs)
=> Add fips support page

.github/workflows/check-links-scheduled.yml
=> Update timeout check-links-scheduled.yml

app/konnect-platform/audit-logs.md, tools/track-docs-changes/config/sources.yml
Fixes #1637 
https://deploy-preview-1812--kongdeveloper.netlify.app/konnect-platform/audit-logs/#how-can-i-verify-konnect-audit-log-signatures
=> Feat: Verify Konnect audit log signatures

app/_indices/gateway.yaml, app/gateway/amazon-rds-authentication-with-aws-iam.md, tools/track-docs-changes/config/sources.yml
Fixes #1628
https://deploy-preview-1810--kongdeveloper.netlify.app/gateway/amazon-rds-authentication-with-aws-iam/
=> Feat: Authenticate your Kong Gateway Amazon RDS database with AWS IAM

app/_includes/how-tos/prereq_cleanup_item.html
=> Liquify cleanup step

app/_plugins/blocks/kuma-specific/kuma.rb
Fixes  https://github.com/Kong/developer.konghq.com/issues/1844
=> Add kuma's demourl plugin

.github/workflows/check-links-scheduled.yml
=> Remove timeout from scheduled broken link checker

app/_includes/plugins/example.md, app/_plugins/drops/plugin_config_example.rb, app/_plugins/generators/plugins/pages/example.rb, app/_plugins/hooks/prune_next_steps_and_related_resources.rb, app/_plugins/lib/link_icon_assigner.rb, app/_plugins/lib/site_accessor.rb, app/konnect-platform/search.md
* [Allow unversioned API links in info boxes](https://github.com/Kong/developer.konghq.com/issues/1894) 
* [min_version doesn't display on plugin examples](https://github.com/Kong/developer.konghq.com/issues/1896)
=> Fix issues

app/_data/products/gateway.yml
Release checklist item.
Fixes https://github.com/Kong/developer.konghq.com/issues/1909
=> Chore: Gateway 3.11 GPG and RSA keys

app/_data/products/gateway.yml, app/_includes/support/gateway.html, app/_plugins/hooks/site_post_write.rb
Related https://github.com/Kong/docs.konghq.com/pull/8867
=> Add api gateway versions page

.github/workflows/update-mesh-metadata.yml
=> Add github action that updates mesh's metadata automatically

app/_how-tos/knep/get-started-with-event-gateway.md, app/_includes/knep/docker-compose-start.md
Issue reported on Slack: https://kongstrong.slack.com/archives/C085YS99K4M/p1750769866104279?thread_ts=1750738250.268639&cid=C085YS99K4M
Ran through the how-to guide, everything worked.
=> Fix: KNEP port

.github/styles/base/Dictionary.txt, app/konnect-platform/audit-logs.md
=> Update audit-logs.md to include support for Crowdstrike parsing standard

app/gateway/incremental-config-sync.md
Fixes #1852 
Fixes #1540 
Originally wanted to write this as a how-to doc, but had a hard time figuring out how to make it a real step-by-step item. 
It's essentially "make these changes to an existing file in your custom plugin", and it just explains what each change does.
Seems to work better as a reference.
Also reframed this as a "special case" rather than a limitation - it's just a behavior adjustment.
https://deploy-preview-1959--kongdeveloper.netlify.app/gateway/incremental-config-sync/#handling-special-cases
=> Incremental config sync with custom plugins

app/_how-tos/use-an-azure-function-through-gateway.md, app/_kong_plugins/azure-functions/index.md
Fixes #816 
If you don't want to go through the whole Azure prereq, you can find the environment variables you need in [1Password](https://share.1password.com/s#WUEc6O_M4Yh1A5zi6fdPaFZIibzavChAZ4d9jLmKXa8).
https://deploy-preview-1946--kongdeveloper.netlify.app/how-to/use-an-azure-function-through-gateway/
=> Feat: Azure Functions how-to

app/_includes/components/prereqs.html
Fixes prereq rendering for KIC
[/kubernetes-ingress-controller/oidc/](https://deploy-preview-8873--kongdocs.netlify.app/kubernetes-ingress-controller/oidc/)
=> Fix works_on for KIC

app/_landing_pages/inso-cli.yaml, app/insomnia/external-vault.md
=> Fix: Add config for external vaults with Inso CLI

app/_landing_pages/dev-portal.yaml, app/dev-portal/portal-customization.md
Fixes #1576 
- https://deploy-preview-1829--kongdeveloper.netlify.app/dev-portal/#customize-dev-portal (moved "Create a Dev Portal" to a button, added a card in Customization for email customization)
- https://deploy-preview-1829--kongdeveloper.netlify.app/dev-portal/portal-customization/#developer-email-customization (new section)
=> feat: Dev Portal email customization

app/_landing_pages/dev-portal.yaml, app/dev-portal/apis.md
Support for AsyncAPI, and validation rules, including how to emulate in CI/CD use cases.
Fixes #issue
TDX-5244
=> AsyncAPI validation rules

app/_includes/landing_pages/button.md, app/_landing_pages/dev-portal.yaml
Follow-up to https://github.com/Kong/developer.konghq.com/pull/1984
=> Fix: Add liquify filter to buttons

app/konnect-platform/network.md
=> fix: Konnect IP address changes

app/_how-tos/synchronize-with-git.md
=> Feat: Update for Insomnia 11.2

app/_kong_plugins/pre-function/examples/add-header-to-request.yaml
Fixes #1855
https://deploy-preview-2021--kongdeveloper.netlify.app/plugins/pre-function/examples/add-header-to-request/
=> Feat: New pre-function example

app/gateway/kong-manager/openid-connect.md
=> Fix: OIDC link

app/gateway/sbom.md
Fixes #1914 
Don't merge until the link exists.
=> chore: SBOM link for gateway 3.11

app/_redirects
Related https://github.com/Kong/docs.konghq.com/pull/8877
Fixes https://github.com/Kong/developer.konghq.com/issues/2032
=> Add redirects to gateway lts for dev-portal and vitals

app/_includes/plugins/ai-proxy/formats.md, app/_includes/plugins/ai-proxy/grouped-upstreams.md, app/_includes/plugins/ai-proxy/overview.md, app/_includes/plugins/ai-proxy/tables/upstream-paths/upstream-paths-azure-ai-proxy.html, app/_includes/plugins/ai-proxy/tables/upstream-paths/upstream-paths-openai-ai-proxy.html
Fixes upstream paths for AI proxy
=> Fix: upstream paths

app/_kong_plugins/ai-aws-guardrails/index.md
=> Fix ai-aws-guardrails metadata

app/_how-tos/write-after-response-script.md, app/_how-tos/write-pre-request-scripts.md, app/_includes/cleanup/products/insomnia.md, app/_indices/insomnia.yaml, app/_landing_pages/insomnia/collections.yaml, app/_landing_pages/insomnia/test.yaml, app/insomnia/allowlist.md, app/insomnia/rbac.md, app/insomnia/scripts.md
Fixes #1428 
Note: some examples from the original docs are missing, but these can be added to the [functions reference](https://github.com/Kong/developer.konghq.com/issues/2076)
https://deploy-preview-2078--kongdeveloper.netlify.app/how-to/write-after-response-script/
https://deploy-preview-2078--kongdeveloper.netlify.app/insomnia/scripts/
=> Feat: Insomnia scripts

app/_landing_pages/dedicated-cloud-gateways.yaml, app/dedicated-cloud-gateways/breaking-changes.md, app/dedicated-cloud-gateways/reference.md
Fixes #1972 
https://kongstrong.slack.com/archives/CDSTDSG9J/p1750949690881489
- added new tile: https://deploy-preview-1983--kongdeveloper.netlify.app/dedicated-cloud-gateways/#more-information
- New page: https://deploy-preview-1983--kongdeveloper.netlify.app/dedicated-cloud-gateways/breaking-changes/
=> Dedicated Cloud Gateway domain breaking changes

app/insomnia/storage.md
Fixes #1640 
https://deploy-preview-2083--kongdeveloper.netlify.app/insomnia/storage/
=> Feat: Git sync for organizations

app/_how-tos/kic-install.md
Fixes https://github.com/Kong/developer.konghq.com/issues/1864
=> Fix kic install guide

.github/workflows/check-links-scheduled.yml
=> Bump setup-ruby

app/_landing_pages/dev-portal.yaml, app/dev-portal/breaking-changes.md, app/dev-portal/custom-domains.md
Add breaking change section regarding custom domain migration.
=> feat: add custom domain migrate breaking changes

app/_data/changelogs/gateway.json, app/_kong_plugins/ai-azure-content-safety/changelog.json, app/_kong_plugins/ai-prompt-decorator/changelog.json, app/_kong_plugins/ai-prompt-guard/changelog.json, app/_kong_plugins/ai-prompt-template/changelog.json, app/_kong_plugins/ai-proxy-advanced/changelog.json, app/_kong_plugins/ai-proxy/changelog.json, app/_kong_plugins/ai-rag-injector/changelog.json, app/_kong_plugins/ai-rate-limiting-advanced/changelog.json, app/_kong_plugins/ai-request-transformer/changelog.json, app/_kong_plugins/ai-response-transformer/changelog.json, app/_kong_plugins/ai-sanitizer/changelog.json, app/_kong_plugins/ai-semantic-cache/changelog.json, app/_kong_plugins/ai-semantic-prompt-guard/changelog.json, app/_kong_plugins/datakit/changelog.json, app/gateway/breaking-changes.md, tools/changelog-generator/missing_entries/3.11.0.0/ai-gateway-license-migration.yml
Will be fixed in an upcoming patch.
https://deploy-preview-2120--kongdeveloper.netlify.app/gateway/changelog/#3-11-0-0-known-issues
https://deploy-preview-2120--kongdeveloper.netlify.app/gateway/breaking-changes/#known-issues-in-3-11-0-0
=> AI Gateway known issue in 3.11

.github/workflows/automated-tests.yaml, tools/automated-tests/docker-helper.js, tools/automated-tests/docker/gateway/Dockerfile
Add GH action that runs the automated-tests every night + workflow_dispatch
=> Add GH action that runs the automated-tests every night

api-specs/gateway/admin-ee/3.11/openapi.yaml
=> Add Admin, Group and RBAC schemas to API 

app/_how-tos/collect-audit-logs.md, app/_how-tos/collect-dev-portal-audit-logs.md, app/_how-tos/get-started-with-gateway.md, app/_indices/konnect-platform.yaml, app/_landing_pages/konnect.yaml, app/_redirects, app/index.html, app/konnect-platform/audit-logs.md, app/konnect-platform/notification-hub.md
A collection of feedback about Konnect docs, part 1.
* Short doc on the Notification Hub
* Rework of the landing page to put apps up, remove tools, add insomnia to apps, and adjust konnect plaform links
* Not sure if the konnect platform section covers the feedback properly, would like to see what reviewers think
* Rework konnect platform index to include konnect apps
* Expose teams and roles on home page
* Adjust audit logs konnect and dev portal docs to not mention the example SIEM provider in the titles
See notes in https://docs.google.com/document/d/1x_jTzYc3wcfR8n0Is7cHgdn4HDXaaIZBii9xejnCAzI/edit?tab=t.0
In a followup, will also:
* rework konnect landing page
* rename konnect-platform to just konnect
https://deploy-preview-2139--kongdeveloper.netlify.app/ …
=> Konnect platform feedback

app/_includes/breadcrumbs.html
=> Fix breadcrumbs on mobile

app/_gateway_entities/vault.md, app/_how-tos/configure-cyberark-as-a-vault-backend.md
Fixes https://kongstrong.slack.com/archives/CDSTDSG9J/p1752583970400339
Also added HCV cert how to to entity page.
- https://deploy-preview-2166--kongdeveloper.netlify.app/how-to/configure-cyberark-as-a-vault-backend/#create-a-vault-entity-for-cyberark-conjur-vault (fixed title)
- https://deploy-preview-2166--kongdeveloper.netlify.app/gateway/entities/vault/#vault-provider-specific-configuration-parameters (docs link under hashicorp tab)
=> Fix: Conjur how to header

app/llms.txt
Fixes #2214 
Add a hardcoded version of this file for now so we can start measuring its impact, we'll change it to an auto-generated one in the future.
=> Add hardcoded llms.txt file for now

app/_how-tos/set-up-ai-proxy-advanced-with-ollama.md, app/_how-tos/set-up-ai-proxy-with-ollama.md
=> fix: set automated tests to false for Ollama how-tos

app/_kong_plugins/request-callout/index.md
Adds a caching paragraph, with info on cache key calculation.
=> plugins: add request-callout caching paragraph

app/konnect-platform/teams-and-roles.md
The Identity Admin role is another means for managing the RBAC configuration in a Konnect organization.
Below is a view of the Administration panel in the role assignments view for a team, user, or system account.
=> doc(rbac): include Identity Admin in verbeage for managing RBAC

app/_api/konnect/service-catalog/_index.md, app/_data/konnect_oas_data.json
=> Service catalog API specs

app/_includes/konnect/dcr-validate.md, app/_landing_pages/dev-portal.yaml, app/dev-portal/analytics.md, app/dev-portal/apis.md, app/dev-portal/pages-and-content.md, app/dev-portal/portal-customization.md, app/dev-portal/publishing.md
Fixes:
- https://kongstrong.slack.com/archives/CDSTDSG9J/p1752739870080619
- https://kongstrong.slack.com/archives/G012HLJ4GJJ/p1752773302337849
- https://kongstrong.slack.com/archives/CDSTDSG9J/p1752747753505569
- https://kongstrong.slack.com/archives/G012HLJ4GJJ/p1753042400943789?thread_ts=1752759492.926299&cid=G012HLJ4GJJ
- #2106 
- https://deploy-preview-2251--kongdeveloper.netlify.app/how-to/azure-ad-dcr/#validate
- https://deploy-preview-2251--kongdeveloper.netlify.app/dev-portal/#how-do-i-view-dev-portal-documentation-for-kong-gateway-3-4
- https://deploy-preview-2251--kongdeveloper.netlify.app/dev-portal/apis/#why-don-t-i-see-api-products-in-my-konnect-sidebar
- https://deploy-preview-2251--kongdeveloper.netlify.app/dev-portal/pages-and-content/#how-do-i-add-an-external-link-to-my- …
=> fixes: Misc Dev Portal feedback fixes

app/ai-gateway/streaming.md
Fixes incorrect SDK code sample for enabling streaming via AI Proxy.
=> Fix: sample code for streaming

app/custom-plugins/python.md
=> Fix typo in python.md

app/_data/changelogs/gateway.json, app/gateway/breaking-changes.md, tools/changelog-generator/missing_entries/3.10.0.0/incremental-sync-stream-mode.yml
Known issue entry for incremental config sync with stream mode.
See https://konghq.atlassian.net/browse/KAG-7376 for details.
https://deploy-preview-2289--kongdeveloper.netlify.app/gateway/breaking-changes/
https://deploy-preview-2289--kongdeveloper.netlify.app/gateway/changelog/#3-10-0-0-known-issues
=> Known issue: Gateway incremental sync

app/_data/glossary.yml
Add community gateway definition + bundled plugin links, instead of linking to plugins that aren't all bundled (third-party).
https://deploy-preview-2292--kongdeveloper.netlify.app/glossary/
=> Glossary additions

app/_landing_pages/event-gateway.yaml
Fixes #2250 
https://deploy-preview-2296--kongdeveloper.netlify.app/event-gateway/#does-knep-run-on-prem
=> FAQ for event gateway on-prem

app/_landing_pages/konnect.yaml
=> Fix: Change messaging on Konnect page

app/_includes/footer.html, app/_includes/header.html, app/_landing_pages/konnect.yaml
Made sure that all links to https://konghq.com/products/kong-konnect/register and https://konghq.com/contact-sales have UTM info.
https://deploy-preview-2331--kongdeveloper.netlify.app/ - see links to "Get a demo" and "Start a free trial" in the top nav and in the footer.
=> Update utm links for konnect

app/gateway/self-managed-migration.md
=> EE to Konnect migration: Add instruction to remove the workspace key

.github/workflows/automated-tests.yaml, .gitignore, tools/automated-tests/config/tests.yaml, tools/automated-tests/instructions-file.js, tools/automated-tests/instructions/extractor.js, tools/automated-tests/instructions/runner.js, tools/automated-tests/reporting.js, tools/automated-tests/run.js
=> Automated tests report

app/_includes/sections/prev_next.html
Fixes [#issue](https://github.com/Kong/developer.konghq.com/issues/1875)
=> Improve the styles of next/previous in Series 

app/_how-tos/create-a-lambda-event-hook-with-kong-gateway.md
Update the doc about the return value of the customized lua codes for an event hook.
Fixes KAG-7423
=> docs(event hooks): update the doc for the lua codes

app/_how-tos/configure-datastore.md
Fixes #2000
https://deploy-preview-2394--kongdeveloper.netlify.app/how-to/configure-datastore/
=> fix: datastore next steps

app/insomnia/accounts.md
Fixes #2302 
https://deploy-preview-2396--kongdeveloper.netlify.app/insomnia/accounts/#why-am-i-not-getting-my-insomnia-login-code-email
=> fix: Insomnia login issue

app/_landing_pages/insomnia/mock-servers.yaml
Fixes #2310 
https://deploy-preview-2397--kongdeveloper.netlify.app/insomnia/mock-servers/#mock-servers-in-insomnia
=> fix: mock url warning

app/gateway/keyring.md
Fixes https://github.com/Kong/docs.konghq.com/issues/8491
https://deploy-preview-2399--kongdeveloper.netlify.app/gateway/keyring/
=> fix: activate recovered key in keyring

api-specs/plugins/vault-auth/openapi.yaml
Fixes # https://github.com/Kong/developer.konghq.com/issues/1186
=> Add missing vault-auth endpoints

.github/styles/base/Dictionary.txt, app/dev-portal/sso.md
Document a Dev Portal IdP configuration example.
=> docs(portal): sso configuration examples

app/_includes/prereqs/tools/deck.md
Fixes #1869 
Any how-to guide with a decK prereq, e.g.: https://deploy-preview-2412--kongdeveloper.netlify.app/mcp/observe-mcp-traffic/
=> fix(deck): Add required version to decK prereq

app/_references/inso-cli/reference/11.4/export.md, app/_references/inso-cli/reference/11.4/export_spec.md, app/_references/inso-cli/reference/11.4/generate-docs.md, app/_references/inso-cli/reference/11.4/index.md, app/_references/inso-cli/reference/11.4/lint.md, app/_references/inso-cli/reference/11.4/lint_spec.md, app/_references/inso-cli/reference/11.4/run.md, app/_references/inso-cli/reference/11.4/run_collection.md, app/_references/inso-cli/reference/11.4/run_test.md, app/_references/inso-cli/reference/11.4/script.md
Fixes #issue
Rebase once [this PR](https://github.com/Kong/developer.konghq.com/pull/2371) is merged to fix the version issue
=> Generate inso-cli docs

netlify/functions/feedback-create.mjs, netlify/functions/feedback-update.mjs, netlify/utils/snowflake.js, package-lock.json, package.json
=> Send feedback to snowflake

app/_indices/insomnia.yaml, app/_landing_pages/insomnia/plugins.yaml, app/insomnia/plugins/context-object-reference.md, app/insomnia/plugins/hooks-and-actions.md, app/insomnia/plugins/plugin-reference.md, app/insomnia/template-tags.md
=> feat: Insomnia plugins

app/_how-tos/okta-oidc-sso-insomnia.md, app/_how-tos/okta-saml-sso-insomnia.md, app/_landing_pages/insomnia/authentication-authorization.yaml, app/insomnia/sso.md
Fixes #2231 
Also review redirect PR: https://github.com/Kong/insomnia-docs/pull/286
- https://deploy-preview-2386--kongdeveloper.netlify.app/how-to/okta-oidc-sso-insomnia/
- https://deploy-preview-2386--kongdeveloper.netlify.app/insomnia/authentication-authorization/#set-up-sso
- https://deploy-preview-2386--kongdeveloper.netlify.app/insomnia/sso/#configure-sso
=> feat: Insomnia Okta OIDC SSO how to

app/_gateway_entities/vault.md, app/_landing_pages/gateway/secrets-management.yaml
Fixes #1888
- https://deploy-preview-2416--kongdeveloper.netlify.app/gateway/entities/vault
- https://deploy-preview-2416--kongdeveloper.netlify.app/gateway/secrets-management/ (also added it here because this doesn't just apply to the Vault entity, you can configure AWS secret manager via environment variables instead of the vault entity)
=> fix: Add AWS vault credential info

docs/README.md, docs/release-checklists.md
Adds release checklists and how to complete each task for Konnect and Gateway.
Netlify preview not relevant here; preview these docs at https://github.com/Kong/developer.konghq.com/blob/feat/release-checklists/docs/release-checklists.md
=> feat(internal-docs): Release checklists for Gateway and Konnect

.github/styles/base/Dictionary.txt, app/_indices/insomnia.yaml, app/insomnia/grpc-requests.md
Fixes #2232 
Please review this as well: https://github.com/Kong/insomnia-docs/pull/285
https://deploy-preview-2378--kongdeveloper.netlify.app/insomnia/grpc-requests/
=> Feat: Migrate Insomnia gRPC page

app/_includes/plugins/ai-proxy/inputs-partials/image-audio/image-edit.md, app/_includes/plugins/ai-proxy/inputs-partials/text/assistants.md
Fixes incorrect samples for image edits and assistants.
=> fix: input samples for images and assistants

app/_includes/support/mesh.html, app/mesh/support-policy.md
=> refactor: how mesh support policy table is generated

app/_how-tos/plugin-dev-add-plugin-testing.md
=> Fix: Update min version for Add custom plugin testing

app/_how-tos/enable-key-auth-for-dev-portal.md, app/_how-tos/enable-oidc-auth-for-dev-portal.md, app/dev-portal/auth-strategies.md
Fixes #1566 
https://deploy-preview-2533--kongdeveloper.netlify.app/how-to/enable-key-auth-for-dev-portal/
=> feat(dev-portal): Key auth how to

app/_data/entity_examples/config.yml, app/_gateway_entities/partial.md, app/_includes/components/entity_example/format/ui.md
Fixes #2419 
https://deploy-preview-2527--kongdeveloper.netlify.app/gateway/entities/partial/
=> Feat: Partials support for Konnect

.github/workflows/sync-preview-branch.yaml
=> feat: add gh action to keep the preview-developer branch in sync with main

.github/workflows/sync-preview-branch.yaml
=> fix: fetch main before reseting the branch

app/_assets/entrypoints/application.js
=> fix: prevent api pages from jumping when scrolling

.github/workflows/sync-preview-branch.yaml
=> fix: don't check out branch before updating it

app/_indices/dev-portal.yaml, app/_landing_pages/dev-portal/self-service.yaml, app/dev-portal/developer-rbac.md, app/dev-portal/developer-signup.md
Fixes #2328 
https://deploy-preview-2578--kongdeveloper.netlify.app/dev-portal/developer-rbac/
=> Feat(dev-portal): Developer RBAC

api-specs/konnect/analytics-dashboards/v2/openapi.yaml
=> Fix: Change Custom dashboards version from v4 -> v2 

app/_how-tos/synchronize-with-git.md, app/insomnia/storage.md
Fixes #2192 
- https://deploy-preview-2592--kongdeveloper.netlify.app/insomnia/storage/#git-sync
- https://deploy-preview-2592--kongdeveloper.netlify.app/how-to/synchronize-with-git/#create-a-project
=> feat(insomnia): Add repo later to Git Sync project in 11.5

app/gateway/debugger.md
Update includes payload capture details
Fixes #2550
=> Feat(debugger): Payload Capture details for debugger

app/insomnia/import-export.md, app/insomnia/storage.md
Fixes https://github.com/Kong/developer.konghq.com/issues/2427
=> Feat(Insomnia): Bulk import 

docs/docs-plugin-toolkit.md
Following discussion in team sync, wrote this doc while generating plugin schemas in https://github.com/Kong/docs-plugin-toolkit/pull/161.
No netlify preview needed. See https://github.com/Kong/developer.konghq.com/blob/feat/plugin-toolkit-doc/docs/docs-plugin-toolkit.md instead.
=> Feat: plugin toolkit process doc

app/_landing_pages/deck.yaml
Issue reported in Slack. 
Fixes https://github.com/Kong/developer.konghq.com/issues/2609
https://deploy-preview-2728--kongdeveloper.netlify.app/deck/
=> Fix(decK): Missing decK completion instructions 

api-specs/gateway/admin-ee/3.11/openapi.yaml
Related to https://github.com/Kong/kong-admin-spec-generator/pull/114
=> Fix: Admin API spec duplicate removal

.github/workflows/gateway-tests.yaml, tools/automated-tests/README.md, tools/automated-tests/runtimes.js
Fixes https://github.com/Kong/developer.konghq.com/issues/2759
Add GH action that runs gateway tests on-demand. 
docker image and tag can be passed as params, (gateway version too, but that's mainly for reporting).
=> feat: Automated tests custom gateway image

.github/workflows/automated-tests.yaml, .github/workflows/gateway-tests.yaml, app/_includes/header.html, app/_plugins/generators/environment_variables.rb, tools/automated-tests/docker/gateway/Dockerfile, tools/automated-tests/instructions/extractor.js, tools/automated-tests/instructions/runner.js, tools/automated-tests/package-lock.json
=> fix: automated-tests dependencies

app/_landing_pages/insomnia.yaml
From:
> DOD:
> Add a note somewhere like in an FAQ the describes how Insomnia gets released:
> 
> New major version twice a year
> New minor version every three weeks (approximately), with beta available a week prior
> Patches when needed
> S: s
Fixes #2437 
- https://deploy-preview-2775--kongdeveloper.netlify.app/insomnia/#how-often-does-insomnia-release-updates
=> Feat (Insomnia) describe insomnia release schedule

app/dev-portal/dynamic-client-registration.md
Add information re/DCR protocol into [Dynamic Client Registration](https://developer.konghq.com/dev-portal/dynamic-client-registration/) article:
> DoD:
> 
> Add DCR protocol explanations to https://developer.konghq.com/dev-portal/dynamic-client-registration/ (content to be provided by Vincent)
> Request: https://kongstrong.slack.com/archives/C02D0BPQC85/p1754923326928189
> Size: S
Fixes #2537 
https://deploy-preview-2740--kongdeveloper.netlify.app/dev-portal/dynamic-client-registration/
=> Fix (dev portal) add DCR protocol explanations

docs/release-checklists.md
Added a step to the Gateway Admin API release steps to run the sync GH action.
N/A
=> fix(internal-docs): Update release checklist

app/_includes/upgrade/hybrid.md, app/gateway/cp-outage.md
Part of https://konghq.atlassian.net/browse/FTI-6892
In combination of https://github.com/Kong/kong-ee/pull/14096
=> feat(gateway): add upgrade notes for fallback config importing/exporting

app/_kong_plugins/ai-azure-content-safety/examples/moderate-requests-and-responses.yaml, app/_kong_plugins/ai-azure-content-safety/examples/moderate-responses.yaml, app/_kong_plugins/ai-azure-content-safety/index.md
Fixes #2205 
Essentially did the same updates as for the AI Sanitizer plugin: https://github.com/Kong/developer.konghq.com/pull/2810
https://deploy-preview-2884--kongdeveloper.netlify.app/plugins/ai-azure-content-safety/
https://deploy-preview-2884--kongdeveloper.netlify.app/plugins/ai-azure-content-safety/examples/moderate-requests-and-responses/
https://deploy-preview-2884--kongdeveloper.netlify.app/plugins/ai-azure-content-safety/examples/moderate-responses/
=> feat(ai-gateway): Azure Content Safety response mode

app/gateway/breaking-changes.md
Release checklist item.
Based on 3.12 changelog.
https://deploy-preview-2881--kongdeveloper.netlify.app/gateway/breaking-changes/
=> chore(gateway): 3.12 breaking changes

app/_kong_plugins/acme/examples/consul.yaml, app/_kong_plugins/acme/examples/kong.yaml, app/_kong_plugins/acme/examples/redis.yaml, app/_kong_plugins/acme/examples/shm.yaml, app/_kong_plugins/acme/examples/vault.yaml
=> chore(acme): update docs of the acme.

netlify/functions/feedback-create.mjs, netlify/utils/snowflake.js
=> fix(feedback): keep the feedback id and update existing row if it exists

app/gateway/breaking-changes.md
Issue reported on Slack multiple times. Also a duplicate of: https://github.com/Kong/developer.konghq.com/pull/2274
=> fix(gateway): Breaking changes version numbers

app/_kong_plugins/ai-aws-guardrails/examples/use-iam-role.yaml, app/_kong_plugins/ai-aws-guardrails/index.md
Fixes #2203
- https://deploy-preview-2844--kongdeveloper.netlify.app/plugins/ai-aws-guardrails/examples/use-iam-role/
- https://deploy-preview-2844--kongdeveloper.netlify.app/plugins/ai-aws-guardrails/
=> feat(ai-gateway): AWS Guardrails plugin IAM support

app/_how-tos/private-hosted-zones.md
Fixes #2643 
- https://deploy-preview-2747--kongdeveloper.netlify.app/dedicated-cloud-gateways/private-hosted-zones/
=> Feat(DCGW): UI instructions for AWS private DNS

app/_gateway_entities/service.md
Feedback came in from user saying this page was confusing. I took a quick look and agreed with them - the way the description was structured and the lack of context to the diagram is really unhelpful.
Adding a flow breakdown and adjusting the description.
https://deploy-preview-2987--kongdeveloper.netlify.app/gateway/entities/service/
=> fix(gateway): Clarify Service explanation

app/_layouts/default.html
=> chore: hide kapa branding

app/_kong_plugins/ai-request-transformer/index.md
=> fix (ai-gateway): Add known failure mode note

app/dev-portal/custom-domains.md
Fixes #2110 
https://deploy-preview-2224--kongdeveloper.netlify.app/dev-portal/custom-domains/
=> feat: Dev Portal: Custom domain certs

app/_landing_pages/konnect-platform/authentication.yaml
update content:
> Do:
> 
> Update https://developer.konghq.com/konnect-platform/authentication/#built-in-ui-authentication-through-konnect with the following information:
> MFA is only required for enterprise users, other new signups can choose if they want to opt into MFA or not
> Aha: https://konghq.aha.io/epics/PLAT-E-31
> 
> S: S
Fixes #2364 
https://deploy-preview-2744--kongdeveloper.netlify.app/konnect-platform/authentication/#built-in-ui-authentication-through-konnect
=> Fix 2364 added information about MFA

app/_includes/konnect/cmek-region-mapping.md, app/_includes/sections/cp-regions.md, app/gateway-manager/aws-private-link.md, app/konnect-platform/network.md
Fixes #2594 
- https://deploy-preview-2933--kongdeveloper.netlify.app/konnect-platform/geos/ 
- https://deploy-preview-2933--kongdeveloper.netlify.app/konnect-platform/network/#hostnames
- https://deploy-preview-2933--kongdeveloper.netlify.app/gateway-manager/aws-private-link/
=> feat(konnect-platform): Singapore support

app/_data/kuma_to_mesh/config.yaml
=> Feat(Mesh): Issue identity with MeshIdentity Spire provider

app/_gateway_entities/service.md
Fixes #2824 
https://deploy-preview-2998--kongdeveloper.netlify.app/gateway/entities/service/#gateway-service-timeouts
=> Feat(Gateway): Service timeouts

app/insomnia/self-hosted-mocks.md
- Updates Insomnia Mockbin self-hosted docs to point explicitly at the self hosted image build.
=> chore: update insomnia mock self-hosted docs

app/_how-tos/gateway-install-helm-onprem.md
Remove references to bitnami, and replace with CNPG
=> Fix(Kubernetes): Postgres fix

app/_data/support/gateway.yml, docs/release-checklists.md
Release checklist item that I just discovered. Adding an internal doc to the checklist so we don't miss it next time.
Don't merge until Gateway is available on Konnect.
=> chore(gateway): Update release dates and checklist for konnect
